import { BlogArticle } from './blogData';

const gizaContentEn = [
  '## Rooms for Rent in Giza 2026: Neighborhoods, Prices & Tips',
  '',
  'Giza is home to millions of Egyptians and hosts major universities like Cairo University, making it one of the busiest rental markets in the country.',
  '',
  '### 1. Dokki (الدقي)',
  '**Average rent:** 3,000 - 6,000 EGP/month per room',
  'Dokki is a central area with excellent metro access (Dokki & Bohooth stations). It\'s popular with Cairo University students and young professionals. The streets are lively with restaurants, cafés, and shops.',
  '',
  '### 2. Mohandessin (المهندسين)',
  '**Average rent:** 3,500 - 7,000 EGP/month per room',
  'Adjacent to Dokki, Mohandessin offers slightly more upscale living with famous streets like Shehab and Gameat El Dowal. Good nightlife and dining scene.',
  '',
  '### 3. Haram & Faisal (الهرم وفيصل)',
  '**Average rent:** 1,500 - 3,500 EGP/month per room',
  'These are the most affordable areas in Giza. They\'re densely populated and busy, but offer the lowest rents. Great for students on a tight budget.',
  '',
  '### 4. 6th of October City (مدينة 6 أكتوبر)',
  '**Average rent:** 2,500 - 5,000 EGP/month per room',
  'A planned city west of Giza with modern infrastructure. Home to multiple private universities (MSA, October University). More spacious apartments but requires a car or bus commute.',
  '',
  '### 5. Sheikh Zayed (الشيخ زايد)',
  '**Average rent:** 4,000 - 8,000 EGP/month per room',
  'An upscale suburb with gated communities and malls like Hyper One and Mall of Arabia. Quieter lifestyle but farther from central Cairo.',
  '',
  '### Tips for Renting in Giza',
  '- **Metro access is key** — Dokki and Mohandessin have direct metro lines',
  '- **Check for student deals** — Many landlords near Cairo University offer student-friendly rates',
  '- **Visit during the day** — Some areas feel different at night',
  '- **Use Sakanak** to find verified listings without broker fees',
  '- **Compare prices** — Giza has a huge range from budget to premium',
].join('\n');

const gizaContentAr = [
  '## غرف للإيجار في الجيزة 2026: الأحياء والأسعار والنصائح',
  '',
  'الجيزة موطن لملايين المصريين وفيها جامعات كبرى زي جامعة القاهرة، مما يخليها من أنشط أسواق الإيجار في البلد.',
  '',
  '### 1. الدقي',
  '**متوسط الإيجار:** 3,000 - 6,000 جنيه/شهر لغرفة',
  'الدقي منطقة مركزية مع وصول ممتاز للمترو. شعبية عند طلاب جامعة القاهرة والشباب.',
  '',
  '### 2. المهندسين',
  '**متوسط الإيجار:** 3,500 - 7,000 جنيه/شهر لغرفة',
  'جنب الدقي، المهندسين بتقدم سكن أرقى مع شوارع شهيرة زي شهاب وجامعة الدول.',
  '',
  '### 3. الهرم وفيصل',
  '**متوسط الإيجار:** 1,500 - 3,500 جنيه/شهر لغرفة',
  'أرخص مناطق في الجيزة. مزدحمة بس بتقدم أقل إيجارات. ممتازة للطلاب.',
  '',
  '### 4. مدينة 6 أكتوبر',
  '**متوسط الإيجار:** 2,500 - 5,000 جنيه/شهر لغرفة',
  'مدينة مخططة غرب الجيزة مع بنية تحتية حديثة. فيها جامعات خاصة كتير.',
  '',
  '### 5. الشيخ زايد',
  '**متوسط الإيجار:** 4,000 - 8,000 جنيه/شهر لغرفة',
  'منطقة راقية فيها كمبوندات ومولات. حياة أهدى بس أبعد عن وسط القاهرة.',
  '',
  '### نصائح للإيجار في الجيزة',
  '- **المترو مهم** — الدقي والمهندسين عندهم مترو مباشر',
  '- **دور على عروض طلاب** — ملاك كتير قرب جامعة القاهرة بيقدموا أسعار للطلاب',
  '- **زور بالنهار** — بعض المناطق مختلفة بالليل',
  '- **استخدم سكنك** لإيجاد إعلانات موثقة بدون عمولة',
].join('\n');

const sharedLivingContentEn = [
  '## 10 Essential Tips for Shared Apartment Living in Egypt',
  '',
  'Living with roommates in Egypt is common and affordable, but it requires clear communication and mutual respect.',
  '',
  '### 1. Set Ground Rules on Day One',
  'Before moving in, agree on cleaning schedules, guest policies, noise hours (especially during exams!), and shared vs. personal food.',
  '',
  '### 2. Split Bills Fairly',
  'Use a shared spreadsheet to track rent (equally or by room size), electricity, water, internet, and shared groceries.',
  '',
  '### 3. Respect Prayer and Study Times',
  'Be mindful of prayer times, Ramadan fasting hours, and exam periods — keep noise levels down.',
  '',
  '### 4. Handle Kitchen Conflicts Early',
  'The kitchen is the #1 source of roommate conflict. Agree on who cleans what and when, shared cooking vs. individual meals.',
  '',
  '### 5. Communicate About Maintenance',
  'Report issues to the landlord together. Split repair costs if not covered by deposit. Don\'t let small issues grow.',
  '',
  '### 6. Establish a Cleaning Routine',
  'Create a weekly rotation for bathroom, kitchen, common areas, and trash.',
  '',
  '### 7. Be Smart About Security',
  'Always lock the door, don\'t share keys with non-residents, agree on a lost-key policy.',
  '',
  '### 8. Plan for Move-Out',
  'Discuss notice period, how to find a replacement roommate, and deposit refund process early.',
  '',
  '### 9. Use Written Agreements',
  'Even among friends, put rent, deposit terms, who\'s on the lease, and notice period in writing.',
  '',
  '### 10. Use Sakanak for Better Matches',
  'Sakanak\'s matching system helps you find compatible roommates based on lifestyle, budget, and preferences — reducing conflicts from the start.',
].join('\n');

const sharedLivingContentAr = [
  '## 10 نصائح أساسية للسكن المشترك في مصر',
  '',
  'السكن مع شركاء سكن في مصر شائع ومعقول التكلفة، بس محتاج تواصل واضح واحترام متبادل.',
  '',
  '### 1. حط قواعد من أول يوم',
  'اتفق على جدول النظافة، سياسة الضيوف، ساعات الهدوء، والأكل المشترك ولا الشخصي.',
  '',
  '### 2. قسم الفواتير بعدل',
  'استخدم جدول مشترك لتتبع الإيجار وفواتير الكهرباء والمياه والإنترنت والمشتريات.',
  '',
  '### 3. احترم أوقات الصلاة والمذاكرة',
  'خلي بالك من أوقات الصلاة، ساعات صيام رمضان، وفترات الامتحانات.',
  '',
  '### 4. حل مشاكل المطبخ بدري',
  'المطبخ هو السبب الأول لخلافات شركاء السكن. اتفق على مين بينضف إيه وإمتى.',
  '',
  '### 5. تواصل عن الصيانة',
  'بلغ صاحب الشقة سوا. قسم تكاليف الإصلاح لو مش مغطاة بالتأمين.',
  '',
  '### 6. حط روتين نظافة',
  'اعمل جدول أسبوعي للحمام والمطبخ والأماكن المشتركة والزبالة.',
  '',
  '### 7. خلي بالك من الأمان',
  'دايماً اقفل الباب، متديش المفتاح لحد من بره، واتفق على سياسة لو المفتاح ضاع.',
  '',
  '### 8. خطط للخروج من الشقة',
  'ناقش بدري عن فترة الإشعار، إزاي تلاقي بديل، واسترداد التأمين.',
  '',
  '### 9. استخدم اتفاقيات مكتوبة',
  'حتى بين الأصحاب، اكتب الإيجار والتأمين ومين على العقد وفترة الإشعار.',
  '',
  '### 10. استخدم سكنك لتوافق أحسن',
  'نظام التوافق في سكنك بيساعدك تلاقي شركاء سكن متوافقين — وده بيقلل الخلافات من البداية.',
].join('\n');

const tenantRightsContentEn = [
  '## Know Your Rights: Tenant Rights When Renting in Egypt',
  '',
  'Many tenants in Egypt are unaware of their legal rights. Here\'s what you need to know.',
  '',
  '### The Rental Contract',
  'In Egypt, a rental agreement should include names and IDs of both parties, property address, monthly rent, contract duration (usually 1 year), deposit amount, and maintenance responsibilities.',
  '',
  '### Your Key Rights as a Tenant',
  '',
  '#### 1. Right to a Written Contract',
  'Always insist on a written contract. Verbal agreements are hard to enforce. Register at the Shahr El Aqari for maximum protection.',
  '',
  '#### 2. Right to Receipt for Payments',
  'You have the right to receive a receipt for every payment — rent, deposit, or utility bills.',
  '',
  '#### 3. Right to Privacy',
  'Your landlord cannot enter without permission, except in emergencies. They must give reasonable notice.',
  '',
  '#### 4. Right to Habitable Conditions',
  'The landlord must maintain working plumbing, electricity, structural safety, and pest control.',
  '',
  '#### 5. Right to Your Deposit Back',
  'Your deposit must be returned when you leave, minus documented damage beyond normal wear and tear.',
  '',
  '### Common Scams to Avoid',
  '- No contract — Never rent without a written agreement',
  '- Deposit theft — Document the apartment with photos when you move in',
  '- Illegal eviction — A landlord cannot force you out before the contract ends',
  '- Hidden fees — All fees should be in the contract',
  '- Fake ownership — Verify the landlord owns the property',
  '',
  '### How Sakanak Protects You',
  '- All users go through ID verification',
  '- In-app booking creates a record',
  '- No hidden broker fees — ever',
].join('\n');

const tenantRightsContentAr = [
  '## اعرف حقوقك: حقوق المستأجر في مصر',
  '',
  'مستأجرين كتير في مصر مش عارفين حقوقهم القانونية. هنا اللي محتاج تعرفه.',
  '',
  '### عقد الإيجار',
  'عقد الإيجار لازم يشمل أسماء وبطاقات الطرفين، عنوان العقار، مبلغ الإيجار، مدة العقد (عادة سنة)، مبلغ التأمين، ومسؤوليات الصيانة.',
  '',
  '### حقوقك الأساسية كمستأجر',
  '',
  '#### 1. الحق في عقد مكتوب',
  'دايماً اصر على عقد مكتوب. الاتفاقات الشفهية صعب تتنفذ. سجل في الشهر العقاري لأقصى حماية.',
  '',
  '#### 2. الحق في إيصال للمدفوعات',
  'من حقك تاخد إيصال لكل دفعة — إيجار أو تأمين أو فواتير.',
  '',
  '#### 3. الحق في الخصوصية',
  'صاحب الشقة مش من حقه يدخل بدون إذنك إلا في حالات الطوارئ.',
  '',
  '#### 4. الحق في ظروف سكن مناسبة',
  'المالك لازم يحافظ على سباكة وكهرباء شغالة وسلامة هيكلية.',
  '',
  '#### 5. الحق في استرداد التأمين',
  'التأمين لازم يترجع لما تمشي، ناقص تلفيات موثقة.',
  '',
  '### نصب شائع لازم تتجنبه',
  '- بدون عقد — متأجرش أبداً بدون اتفاق مكتوب',
  '- سرقة التأمين — وثق حالة الشقة بصور لما تنقل',
  '- طرد غير قانوني — المالك مش من حقه يطردك قبل ما العقد ينتهي',
  '- رسوم مخفية — كل الرسوم لازم تكون في العقد',
  '',
  '### إزاي سكنك بتحميك',
  '- كل المستخدمين بيتحققوا من هويتهم',
  '- الحجز والتواصل داخل التطبيق بيعمل سجل',
  '- مفيش عمولة سمسار مخفية — أبداً',
].join('\n');

const costComparisonContentEn = [
  '## Cost of Living & Rent Comparison: Cairo vs Alexandria vs Mansoura',
  '',
  'Choosing where to live in Egypt often comes down to budget. Here\'s a detailed comparison.',
  '',
  '### Rent Comparison (per room, shared apartment)',
  '',
  '| Category | Cairo | Alexandria | Mansoura |',
  '|----------|-------|------------|----------|',
  '| Budget area | 2,000-4,000 EGP | 1,500-3,000 EGP | 1,200-2,500 EGP |',
  '| Mid-range | 4,000-7,000 EGP | 3,000-5,000 EGP | 2,000-3,500 EGP |',
  '| Premium | 7,000-12,000 EGP | 5,000-8,000 EGP | 3,000-5,000 EGP |',
  '',
  '### Monthly Expenses Breakdown',
  '',
  '**Food & Groceries:** Cairo 3,000-5,000 | Alexandria 2,500-4,000 | Mansoura 2,000-3,500 EGP',
  '',
  '**Transportation:** Cairo 800-2,000 | Alexandria 500-1,200 | Mansoura 300-800 EGP',
  '',
  '**Utilities (shared):** Cairo 300-600 | Alexandria 250-500 | Mansoura 200-400 EGP/person',
  '',
  '### Total Monthly Budget (per person)',
  '',
  '| Level | Cairo | Alexandria | Mansoura |',
  '|-------|-------|------------|----------|',
  '| Student/Budget | 6,000-9,000 | 4,500-7,000 | 3,500-5,500 EGP |',
  '| Comfortable | 9,000-15,000 | 7,000-11,000 | 5,500-8,000 EGP |',
  '',
  '### Which City is Right for You?',
  '',
  '**Choose Cairo if** you work in a corporate or tech job and want the most entertainment options.',
  '',
  '**Choose Alexandria if** you want a relaxed lifestyle by the sea with lower costs than Cairo.',
  '',
  '**Choose Mansoura if** budget is your top priority or you study at Mansoura University.',
  '',
  '### Save Money Everywhere with Sakanak',
  'Use Sakanak to find rooms directly from verified owners — no broker fees — and compare prices across neighborhoods.',
].join('\n');

const costComparisonContentAr = [
  '## مقارنة تكاليف المعيشة والإيجار: القاهرة vs الاسكندرية vs المنصورة',
  '',
  'اختيار مكان السكن في مصر غالباً بيرجع للميزانية. هنا مقارنة تفصيلية.',
  '',
  '### مقارنة الإيجارات (لغرفة في شقة مشاركة)',
  '',
  '| الفئة | القاهرة | الاسكندرية | المنصورة |',
  '|-------|---------|------------|----------|',
  '| منطقة اقتصادية | 2,000-4,000 | 1,500-3,000 | 1,200-2,500 جنيه |',
  '| منطقة متوسطة | 4,000-7,000 | 3,000-5,000 | 2,000-3,500 جنيه |',
  '| منطقة راقية | 7,000-12,000 | 5,000-8,000 | 3,000-5,000 جنيه |',
  '',
  '### تفصيل المصاريف الشهرية',
  '',
  '**الأكل والبقالة:** القاهرة 3,000-5,000 | الاسكندرية 2,500-4,000 | المنصورة 2,000-3,500 جنيه',
  '',
  '**المواصلات:** القاهرة 800-2,000 | الاسكندرية 500-1,200 | المنصورة 300-800 جنيه',
  '',
  '**الفواتير (مشتركة):** القاهرة 300-600 | الاسكندرية 250-500 | المنصورة 200-400 جنيه/فرد',
  '',
  '### أي مدينة مناسبة ليك؟',
  '',
  '**اختار القاهرة لو** بتشتغل في شركة أو تكنولوجيا وعايز أكتر خيارات ترفيه.',
  '',
  '**اختار الاسكندرية لو** عايز حياة أهدى على البحر مع تكاليف أقل.',
  '',
  '**اختار المنصورة لو** الميزانية أهم أولوياتك أو بتدرس في جامعة المنصورة.',
  '',
  '### وفر فلوس مع سكنك',
  'استخدم سكنك لإيجاد غرف مباشرة من ملاك موثقين — بدون عمولة — وقارن الأسعار.',
].join('\n');

const newCairoContentEn = [
  '## Rooms for Rent in New Cairo & Fifth Settlement: 2026 Guide',
  '',
  'New Cairo has become one of Egypt\'s most desirable residential areas, especially for students and young professionals.',
  '',
  '### Why New Cairo?',
  '- Home to AUC and GUC',
  '- Modern infrastructure with wide roads and green spaces',
  '- Major malls: Cairo Festival City, Point 90',
  '- Growing job market',
  '',
  '### Best Neighborhoods',
  '',
  '#### Fifth Settlement (التجمع الخامس)',
  '**Average rent:** 4,000 - 8,000 EGP/month per room',
  'The heart of New Cairo with excellent amenities. Close to AUC.',
  '',
  '#### Rehab City (مدينة الرحاب)',
  '**Average rent:** 3,500 - 6,000 EGP/month per room',
  'Self-contained community with its own mall, schools, and clinics.',
  '',
  '#### Madinaty (مدينتي)',
  '**Average rent:** 3,000 - 5,500 EGP/month per room',
  'Egypt\'s largest residential compound. Very green and family-friendly.',
  '',
  '#### Beit Al Watan (بيت الوطن)',
  '**Average rent:** 3,000 - 5,000 EGP/month per room',
  'Newer area with competitive prices. Good for budget-conscious renters.',
  '',
  '#### Shorouk City (مدينة الشروق)',
  '**Average rent:** 2,500 - 4,500 EGP/month per room',
  'Adjacent to New Cairo with lower prices. Popular with students.',
  '',
  '### Transportation Tips',
  '- No metro access yet — relies on buses and cars',
  '- CTA buses connect to central Cairo',
  '- AUC and GUC offer student transportation',
  '- Carpooling with roommates is common',
  '',
  '### Tips for New Cairo Renters',
  '- Check water pressure — some newer buildings have issues',
  '- Verify compound rules — some don\'t allow sharing',
  '- Check internet coverage before committing',
  '- Use Sakanak for verified, broker-free listings',
].join('\n');

const newCairoContentAr = [
  '## غرف للإيجار في القاهرة الجديدة والتجمع الخامس: دليل 2026',
  '',
  'القاهرة الجديدة بقت واحدة من أكثر المناطق السكنية المرغوبة في مصر.',
  '',
  '### ليه القاهرة الجديدة؟',
  '- فيها الجامعة الأمريكية والجامعة الألمانية',
  '- بنية تحتية حديثة مع شوارع واسعة',
  '- مولات كبيرة: كايرو فستيفال سيتي، بوينت 90',
  '- سوق عمل بيكبر',
  '',
  '### أفضل الأحياء',
  '',
  '#### التجمع الخامس',
  '**متوسط الإيجار:** 4,000 - 8,000 جنيه/شهر لغرفة',
  'قلب القاهرة الجديدة. قريب من الجامعة الأمريكية.',
  '',
  '#### مدينة الرحاب',
  '**متوسط الإيجار:** 3,500 - 6,000 جنيه/شهر لغرفة',
  'مجتمع مكتفي ذاتياً فيه مول ومدارس وعيادات.',
  '',
  '#### مدينتي',
  '**متوسط الإيجار:** 3,000 - 5,500 جنيه/شهر لغرفة',
  'أكبر كمبوند سكني في مصر. أخضر جداً.',
  '',
  '#### بيت الوطن',
  '**متوسط الإيجار:** 3,000 - 5,000 جنيه/شهر لغرفة',
  'منطقة جديدة بأسعار تنافسية.',
  '',
  '#### مدينة الشروق',
  '**متوسط الإيجار:** 2,500 - 4,500 جنيه/شهر لغرفة',
  'جنب القاهرة الجديدة بأسعار أقل. شعبية عند الطلاب.',
  '',
  '### نصائح المواصلات',
  '- مفيش مترو لسه — بتعتمد على الأتوبيسات والعربيات',
  '- أتوبيسات CTA بتوصل وسط القاهرة',
  '- الجامعة الأمريكية والألمانية بيوفروا نقل للطلاب',
  '- المشاركة في التوصيل مع شركاء السكن شائعة',
  '',
  '### نصائح لمستأجري القاهرة الجديدة',
  '- تأكد من ضغط المياه',
  '- تحقق من قوانين الكمبوند — بعضها مش بيسمح بالمشاركة',
  '- تأكد من تغطية الإنترنت',
  '- استخدم سكنك لإعلانات موثقة بدون سمسار',
].join('\n');

export const EXTRA_BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'rooms-for-rent-giza-2026',
    titleEn: 'Rooms for Rent in Giza 2026: Neighborhoods, Prices & Tips',
    titleAr: 'غرف للإيجار في الجيزة 2026: الأحياء والأسعار والنصائح',
    excerptEn: 'Discover the best areas to rent a room in Giza, from Dokki and Mohandessin to 6th of October City, with updated prices.',
    excerptAr: 'اكتشف أفضل المناطق لإيجار غرفة في الجيزة، من الدقي والمهندسين لمدينة 6 أكتوبر، مع أسعار محدثة.',
    contentEn: gizaContentEn,
    contentAr: gizaContentAr,
    keywords: 'rooms for rent Giza, غرف للايجار في الجيزة, rent Giza 2026, إيجار الجيزة, Dokki rent, الدقي إيجار, Mohandessin rent, المهندسين إيجار, 6th October rent, Haram Faisal rent',
    publishedAt: '2026-03-08',
    readTimeMin: 5,
    category: 'city',
  },
  {
    slug: 'shared-apartment-living-tips-egypt',
    titleEn: '10 Essential Tips for Shared Apartment Living in Egypt',
    titleAr: '10 نصائح أساسية للسكن المشترك في مصر',
    excerptEn: 'Make your shared apartment experience smooth and conflict-free with these practical tips for Egyptian flatmates.',
    excerptAr: 'اجعل تجربة السكن المشترك سلسة وبدون مشاكل مع النصائح العملية دي.',
    contentEn: sharedLivingContentEn,
    contentAr: sharedLivingContentAr,
    keywords: 'shared apartment Egypt, شقة مشاركة مصر, roommate tips, نصائح شريك سكن, flat sharing Egypt, سكن مشترك, living with roommates Egypt',
    publishedAt: '2026-03-06',
    readTimeMin: 6,
    category: 'tips',
  },
  {
    slug: 'tenant-rights-renting-egypt',
    titleEn: 'Know Your Rights: Tenant Rights When Renting in Egypt',
    titleAr: 'اعرف حقوقك: حقوق المستأجر في مصر',
    excerptEn: 'Understanding your legal rights as a tenant in Egypt can protect you from scams and unfair practices.',
    excerptAr: 'فهم حقوقك القانونية كمستأجر في مصر بيحميك من النصب والممارسات غير العادلة.',
    contentEn: tenantRightsContentEn,
    contentAr: tenantRightsContentAr,
    keywords: 'tenant rights Egypt, حقوق المستأجر في مصر, rental contract Egypt, عقد إيجار مصر, renting scams Egypt, نصب الإيجار, landlord tenant law Egypt',
    publishedAt: '2026-03-04',
    readTimeMin: 6,
    category: 'guides',
  },
  {
    slug: 'cost-of-living-comparison-egyptian-cities',
    titleEn: 'Cost of Living & Rent Comparison: Cairo vs Alexandria vs Mansoura',
    titleAr: 'مقارنة تكاليف المعيشة والإيجار: القاهرة vs الاسكندرية vs المنصورة',
    excerptEn: 'Compare rent, food, transport and total monthly costs across Egypt\'s top 3 cities for room seekers.',
    excerptAr: 'قارن الإيجار والأكل والمواصلات والتكاليف الشهرية في أكبر 3 مدن في مصر.',
    contentEn: costComparisonContentEn,
    contentAr: costComparisonContentAr,
    keywords: 'cost of living Egypt, تكاليف المعيشة مصر, rent comparison Cairo Alexandria, مقارنة إيجار, cheapest cities Egypt, أرخص مدن مصر, Mansoura rent, المنصورة إيجار',
    publishedAt: '2026-03-02',
    readTimeMin: 7,
    category: 'guides',
  },
  {
    slug: 'new-cairo-fifth-settlement-rooms-guide',
    titleEn: 'Rooms for Rent in New Cairo & Fifth Settlement: 2026 Guide',
    titleAr: 'غرف للإيجار في القاهرة الجديدة والتجمع الخامس: دليل 2026',
    excerptEn: 'Find affordable rooms and shared apartments near AUC, the German University, and top compounds in New Cairo.',
    excerptAr: 'لاقي غرف بأسعار معقولة وشقق مشاركة بالقرب من الجامعة الأمريكية والألمانية في القاهرة الجديدة.',
    contentEn: newCairoContentEn,
    contentAr: newCairoContentAr,
    keywords: 'rooms New Cairo, غرف للايجار القاهرة الجديدة, Fifth Settlement rent, التجمع الخامس إيجار, AUC housing, سكن الجامعة الأمريكية, Rehab City rent, الرحاب إيجار, Madinaty rent, مدينتي إيجار',
    publishedAt: '2026-03-07',
    readTimeMin: 7,
    category: 'city',
  },
];
