// Comprehensive list of world nationalities (UN member states + commonly recognized)
// Used by signup form and Complete Profile page.

export interface NationalityOption {
  value: string;
  labelEn: string;
  labelAr: string;
}

export const NATIONALITIES: NationalityOption[] = [
  // Arab world (kept on top for primary audience)
  { value: 'egyptian', labelEn: 'Egyptian', labelAr: 'مصري' },
  { value: 'saudi', labelEn: 'Saudi', labelAr: 'سعودي' },
  { value: 'emirati', labelEn: 'Emirati', labelAr: 'إماراتي' },
  { value: 'kuwaiti', labelEn: 'Kuwaiti', labelAr: 'كويتي' },
  { value: 'qatari', labelEn: 'Qatari', labelAr: 'قطري' },
  { value: 'bahraini', labelEn: 'Bahraini', labelAr: 'بحريني' },
  { value: 'omani', labelEn: 'Omani', labelAr: 'عماني' },
  { value: 'jordanian', labelEn: 'Jordanian', labelAr: 'أردني' },
  { value: 'lebanese', labelEn: 'Lebanese', labelAr: 'لبناني' },
  { value: 'syrian', labelEn: 'Syrian', labelAr: 'سوري' },
  { value: 'palestinian', labelEn: 'Palestinian', labelAr: 'فلسطيني' },
  { value: 'iraqi', labelEn: 'Iraqi', labelAr: 'عراقي' },
  { value: 'yemeni', labelEn: 'Yemeni', labelAr: 'يمني' },
  { value: 'libyan', labelEn: 'Libyan', labelAr: 'ليبي' },
  { value: 'tunisian', labelEn: 'Tunisian', labelAr: 'تونسي' },
  { value: 'algerian', labelEn: 'Algerian', labelAr: 'جزائري' },
  { value: 'moroccan', labelEn: 'Moroccan', labelAr: 'مغربي' },
  { value: 'mauritanian', labelEn: 'Mauritanian', labelAr: 'موريتاني' },
  { value: 'sudanese', labelEn: 'Sudanese', labelAr: 'سوداني' },
  { value: 'south_sudanese', labelEn: 'South Sudanese', labelAr: 'جنوب سوداني' },
  { value: 'somali', labelEn: 'Somali', labelAr: 'صومالي' },
  { value: 'djiboutian', labelEn: 'Djiboutian', labelAr: 'جيبوتي' },
  { value: 'comorian', labelEn: 'Comorian', labelAr: 'قمري' },

  // Africa
  { value: 'angolan', labelEn: 'Angolan', labelAr: 'أنغولي' },
  { value: 'beninese', labelEn: 'Beninese', labelAr: 'بنيني' },
  { value: 'botswanan', labelEn: 'Botswanan', labelAr: 'بوتسواني' },
  { value: 'burkinabe', labelEn: 'Burkinabé', labelAr: 'بوركيني' },
  { value: 'burundian', labelEn: 'Burundian', labelAr: 'بوروندي' },
  { value: 'cameroonian', labelEn: 'Cameroonian', labelAr: 'كاميروني' },
  { value: 'cape_verdean', labelEn: 'Cape Verdean', labelAr: 'رأس الأخضر' },
  { value: 'central_african', labelEn: 'Central African', labelAr: 'أفريقي وسطى' },
  { value: 'chadian', labelEn: 'Chadian', labelAr: 'تشادي' },
  { value: 'congolese', labelEn: 'Congolese', labelAr: 'كونغولي' },
  { value: 'congolese_drc', labelEn: 'Congolese (DRC)', labelAr: 'كونغولي (جمهورية الكونغو الديمقراطية)' },
  { value: 'ivorian', labelEn: 'Ivorian', labelAr: 'إيفواري' },
  { value: 'equatorial_guinean', labelEn: 'Equatorial Guinean', labelAr: 'غيني استوائي' },
  { value: 'eritrean', labelEn: 'Eritrean', labelAr: 'إريتري' },
  { value: 'eswatini', labelEn: 'Swazi', labelAr: 'سوازيلندي' },
  { value: 'ethiopian', labelEn: 'Ethiopian', labelAr: 'إثيوبي' },
  { value: 'gabonese', labelEn: 'Gabonese', labelAr: 'غابوني' },
  { value: 'gambian', labelEn: 'Gambian', labelAr: 'غامبي' },
  { value: 'ghanaian', labelEn: 'Ghanaian', labelAr: 'غاني' },
  { value: 'guinean', labelEn: 'Guinean', labelAr: 'غيني' },
  { value: 'guinea_bissauan', labelEn: 'Guinea-Bissauan', labelAr: 'غيني بيساوي' },
  { value: 'kenyan', labelEn: 'Kenyan', labelAr: 'كيني' },
  { value: 'lesotho', labelEn: 'Mosotho', labelAr: 'ليسوتي' },
  { value: 'liberian', labelEn: 'Liberian', labelAr: 'ليبيري' },
  { value: 'malagasy', labelEn: 'Malagasy', labelAr: 'مدغشقري' },
  { value: 'malawian', labelEn: 'Malawian', labelAr: 'مالاوي' },
  { value: 'malian', labelEn: 'Malian', labelAr: 'مالي' },
  { value: 'mauritian', labelEn: 'Mauritian', labelAr: 'موريشيوسي' },
  { value: 'mozambican', labelEn: 'Mozambican', labelAr: 'موزمبيقي' },
  { value: 'namibian', labelEn: 'Namibian', labelAr: 'ناميبي' },
  { value: 'nigerien', labelEn: 'Nigerien', labelAr: 'نيجري' },
  { value: 'nigerian', labelEn: 'Nigerian', labelAr: 'نيجيري' },
  { value: 'rwandan', labelEn: 'Rwandan', labelAr: 'رواندي' },
  { value: 'sao_tomean', labelEn: 'São Toméan', labelAr: 'ساو تومي' },
  { value: 'senegalese', labelEn: 'Senegalese', labelAr: 'سنغالي' },
  { value: 'seychellois', labelEn: 'Seychellois', labelAr: 'سيشلي' },
  { value: 'sierra_leonean', labelEn: 'Sierra Leonean', labelAr: 'سيراليوني' },
  { value: 'south_african', labelEn: 'South African', labelAr: 'جنوب أفريقي' },
  { value: 'tanzanian', labelEn: 'Tanzanian', labelAr: 'تنزاني' },
  { value: 'togolese', labelEn: 'Togolese', labelAr: 'توغولي' },
  { value: 'ugandan', labelEn: 'Ugandan', labelAr: 'أوغندي' },
  { value: 'zambian', labelEn: 'Zambian', labelAr: 'زامبي' },
  { value: 'zimbabwean', labelEn: 'Zimbabwean', labelAr: 'زيمبابوي' },

  // Europe
  { value: 'albanian', labelEn: 'Albanian', labelAr: 'ألباني' },
  { value: 'andorran', labelEn: 'Andorran', labelAr: 'أندوري' },
  { value: 'armenian', labelEn: 'Armenian', labelAr: 'أرميني' },
  { value: 'austrian', labelEn: 'Austrian', labelAr: 'نمساوي' },
  { value: 'azerbaijani', labelEn: 'Azerbaijani', labelAr: 'أذربيجاني' },
  { value: 'belarusian', labelEn: 'Belarusian', labelAr: 'بيلاروسي' },
  { value: 'belgian', labelEn: 'Belgian', labelAr: 'بلجيكي' },
  { value: 'bosnian', labelEn: 'Bosnian', labelAr: 'بوسني' },
  { value: 'british', labelEn: 'British', labelAr: 'بريطاني' },
  { value: 'bulgarian', labelEn: 'Bulgarian', labelAr: 'بلغاري' },
  { value: 'croatian', labelEn: 'Croatian', labelAr: 'كرواتي' },
  { value: 'cypriot', labelEn: 'Cypriot', labelAr: 'قبرصي' },
  { value: 'czech', labelEn: 'Czech', labelAr: 'تشيكي' },
  { value: 'danish', labelEn: 'Danish', labelAr: 'دنماركي' },
  { value: 'dutch', labelEn: 'Dutch', labelAr: 'هولندي' },
  { value: 'estonian', labelEn: 'Estonian', labelAr: 'إستوني' },
  { value: 'finnish', labelEn: 'Finnish', labelAr: 'فنلندي' },
  { value: 'french', labelEn: 'French', labelAr: 'فرنسي' },
  { value: 'georgian', labelEn: 'Georgian', labelAr: 'جورجي' },
  { value: 'german', labelEn: 'German', labelAr: 'ألماني' },
  { value: 'greek', labelEn: 'Greek', labelAr: 'يوناني' },
  { value: 'hungarian', labelEn: 'Hungarian', labelAr: 'مجري' },
  { value: 'icelandic', labelEn: 'Icelandic', labelAr: 'آيسلندي' },
  { value: 'irish', labelEn: 'Irish', labelAr: 'إيرلندي' },
  { value: 'italian', labelEn: 'Italian', labelAr: 'إيطالي' },
  { value: 'kosovar', labelEn: 'Kosovar', labelAr: 'كوسوفي' },
  { value: 'latvian', labelEn: 'Latvian', labelAr: 'لاتفي' },
  { value: 'liechtensteiner', labelEn: 'Liechtensteiner', labelAr: 'ليختنشتايني' },
  { value: 'lithuanian', labelEn: 'Lithuanian', labelAr: 'ليتواني' },
  { value: 'luxembourger', labelEn: 'Luxembourger', labelAr: 'لوكسمبورغي' },
  { value: 'macedonian', labelEn: 'Macedonian', labelAr: 'مقدوني' },
  { value: 'maltese', labelEn: 'Maltese', labelAr: 'مالطي' },
  { value: 'moldovan', labelEn: 'Moldovan', labelAr: 'مولدوفي' },
  { value: 'monacan', labelEn: 'Monacan', labelAr: 'موناكي' },
  { value: 'montenegrin', labelEn: 'Montenegrin', labelAr: 'جبل أسود' },
  { value: 'norwegian', labelEn: 'Norwegian', labelAr: 'نرويجي' },
  { value: 'polish', labelEn: 'Polish', labelAr: 'بولندي' },
  { value: 'portuguese', labelEn: 'Portuguese', labelAr: 'برتغالي' },
  { value: 'romanian', labelEn: 'Romanian', labelAr: 'روماني' },
  { value: 'russian', labelEn: 'Russian', labelAr: 'روسي' },
  { value: 'san_marinese', labelEn: 'San Marinese', labelAr: 'سان ماريني' },
  { value: 'serbian', labelEn: 'Serbian', labelAr: 'صربي' },
  { value: 'slovak', labelEn: 'Slovak', labelAr: 'سلوفاكي' },
  { value: 'slovenian', labelEn: 'Slovenian', labelAr: 'سلوفيني' },
  { value: 'spanish', labelEn: 'Spanish', labelAr: 'إسباني' },
  { value: 'swedish', labelEn: 'Swedish', labelAr: 'سويدي' },
  { value: 'swiss', labelEn: 'Swiss', labelAr: 'سويسري' },
  { value: 'turkish', labelEn: 'Turkish', labelAr: 'تركي' },
  { value: 'ukrainian', labelEn: 'Ukrainian', labelAr: 'أوكراني' },
  { value: 'vatican', labelEn: 'Vatican', labelAr: 'فاتيكاني' },

  // Asia
  { value: 'afghan', labelEn: 'Afghan', labelAr: 'أفغاني' },
  { value: 'bangladeshi', labelEn: 'Bangladeshi', labelAr: 'بنغلاديشي' },
  { value: 'bhutanese', labelEn: 'Bhutanese', labelAr: 'بوتاني' },
  { value: 'bruneian', labelEn: 'Bruneian', labelAr: 'بروناي' },
  { value: 'burmese', labelEn: 'Burmese (Myanmar)', labelAr: 'بورمي (ميانمار)' },
  { value: 'cambodian', labelEn: 'Cambodian', labelAr: 'كمبودي' },
  { value: 'chinese', labelEn: 'Chinese', labelAr: 'صيني' },
  { value: 'east_timorese', labelEn: 'East Timorese', labelAr: 'تيموري شرقي' },
  { value: 'filipino', labelEn: 'Filipino', labelAr: 'فلبيني' },
  { value: 'hong_konger', labelEn: 'Hong Konger', labelAr: 'هونغ كونغي' },
  { value: 'indian', labelEn: 'Indian', labelAr: 'هندي' },
  { value: 'indonesian', labelEn: 'Indonesian', labelAr: 'إندونيسي' },
  { value: 'iranian', labelEn: 'Iranian', labelAr: 'إيراني' },
  { value: 'israeli', labelEn: 'Israeli', labelAr: 'إسرائيلي' },
  { value: 'japanese', labelEn: 'Japanese', labelAr: 'ياباني' },
  { value: 'kazakh', labelEn: 'Kazakh', labelAr: 'كازاخي' },
  { value: 'korean', labelEn: 'Korean (South)', labelAr: 'كوري (جنوبي)' },
  { value: 'north_korean', labelEn: 'Korean (North)', labelAr: 'كوري (شمالي)' },
  { value: 'kyrgyz', labelEn: 'Kyrgyz', labelAr: 'قيرغيزي' },
  { value: 'laotian', labelEn: 'Laotian', labelAr: 'لاوسي' },
  { value: 'malaysian', labelEn: 'Malaysian', labelAr: 'ماليزي' },
  { value: 'maldivian', labelEn: 'Maldivian', labelAr: 'مالديفي' },
  { value: 'mongolian', labelEn: 'Mongolian', labelAr: 'منغولي' },
  { value: 'nepali', labelEn: 'Nepali', labelAr: 'نيبالي' },
  { value: 'pakistani', labelEn: 'Pakistani', labelAr: 'باكستاني' },
  { value: 'singaporean', labelEn: 'Singaporean', labelAr: 'سنغافوري' },
  { value: 'sri_lankan', labelEn: 'Sri Lankan', labelAr: 'سريلانكي' },
  { value: 'taiwanese', labelEn: 'Taiwanese', labelAr: 'تايواني' },
  { value: 'tajik', labelEn: 'Tajik', labelAr: 'طاجيكي' },
  { value: 'thai', labelEn: 'Thai', labelAr: 'تايلاندي' },
  { value: 'turkmen', labelEn: 'Turkmen', labelAr: 'تركماني' },
  { value: 'uzbek', labelEn: 'Uzbek', labelAr: 'أوزبكي' },
  { value: 'vietnamese', labelEn: 'Vietnamese', labelAr: 'فيتنامي' },

  // Americas
  { value: 'american', labelEn: 'American', labelAr: 'أمريكي' },
  { value: 'antiguan', labelEn: 'Antiguan', labelAr: 'أنتيغوي' },
  { value: 'argentine', labelEn: 'Argentine', labelAr: 'أرجنتيني' },
  { value: 'bahamian', labelEn: 'Bahamian', labelAr: 'باهامي' },
  { value: 'barbadian', labelEn: 'Barbadian', labelAr: 'بربادوسي' },
  { value: 'belizean', labelEn: 'Belizean', labelAr: 'بليزي' },
  { value: 'bolivian', labelEn: 'Bolivian', labelAr: 'بوليفي' },
  { value: 'brazilian', labelEn: 'Brazilian', labelAr: 'برازيلي' },
  { value: 'canadian', labelEn: 'Canadian', labelAr: 'كندي' },
  { value: 'chilean', labelEn: 'Chilean', labelAr: 'تشيلي' },
  { value: 'colombian', labelEn: 'Colombian', labelAr: 'كولومبي' },
  { value: 'costa_rican', labelEn: 'Costa Rican', labelAr: 'كوستاريكي' },
  { value: 'cuban', labelEn: 'Cuban', labelAr: 'كوبي' },
  { value: 'dominican', labelEn: 'Dominican', labelAr: 'دومينيكي' },
  { value: 'dominican_rep', labelEn: 'Dominican (Republic)', labelAr: 'دومينيكاني' },
  { value: 'ecuadorian', labelEn: 'Ecuadorian', labelAr: 'إكوادوري' },
  { value: 'salvadoran', labelEn: 'Salvadoran', labelAr: 'سلفادوري' },
  { value: 'grenadian', labelEn: 'Grenadian', labelAr: 'غريناداوي' },
  { value: 'guatemalan', labelEn: 'Guatemalan', labelAr: 'غواتيمالي' },
  { value: 'guyanese', labelEn: 'Guyanese', labelAr: 'غيانائي' },
  { value: 'haitian', labelEn: 'Haitian', labelAr: 'هايتي' },
  { value: 'honduran', labelEn: 'Honduran', labelAr: 'هندوراسي' },
  { value: 'jamaican', labelEn: 'Jamaican', labelAr: 'جامايكي' },
  { value: 'mexican', labelEn: 'Mexican', labelAr: 'مكسيكي' },
  { value: 'nicaraguan', labelEn: 'Nicaraguan', labelAr: 'نيكاراغوي' },
  { value: 'panamanian', labelEn: 'Panamanian', labelAr: 'بنمي' },
  { value: 'paraguayan', labelEn: 'Paraguayan', labelAr: 'باراغواي' },
  { value: 'peruvian', labelEn: 'Peruvian', labelAr: 'بيروفي' },
  { value: 'puerto_rican', labelEn: 'Puerto Rican', labelAr: 'بورتوريكي' },
  { value: 'kittitian', labelEn: 'Kittitian / Nevisian', labelAr: 'كيتيسي / نيفيسي' },
  { value: 'saint_lucian', labelEn: 'Saint Lucian', labelAr: 'سانت لوسي' },
  { value: 'vincentian', labelEn: 'Vincentian', labelAr: 'فينسنتي' },
  { value: 'surinamese', labelEn: 'Surinamese', labelAr: 'سورينامي' },
  { value: 'trinidadian', labelEn: 'Trinidadian', labelAr: 'تريندادي' },
  { value: 'uruguayan', labelEn: 'Uruguayan', labelAr: 'أوروغواي' },
  { value: 'venezuelan', labelEn: 'Venezuelan', labelAr: 'فنزويلي' },

  // Oceania
  { value: 'australian', labelEn: 'Australian', labelAr: 'أسترالي' },
  { value: 'fijian', labelEn: 'Fijian', labelAr: 'فيجي' },
  { value: 'i_kiribati', labelEn: 'I-Kiribati', labelAr: 'كيريباتي' },
  { value: 'marshallese', labelEn: 'Marshallese', labelAr: 'مارشالي' },
  { value: 'micronesian', labelEn: 'Micronesian', labelAr: 'ميكرونيزي' },
  { value: 'nauruan', labelEn: 'Nauruan', labelAr: 'ناورو' },
  { value: 'new_zealander', labelEn: 'New Zealander', labelAr: 'نيوزيلندي' },
  { value: 'palauan', labelEn: 'Palauan', labelAr: 'بالاوي' },
  { value: 'papua_new_guinean', labelEn: 'Papua New Guinean', labelAr: 'بابوا غينيا الجديدة' },
  { value: 'samoan', labelEn: 'Samoan', labelAr: 'ساموي' },
  { value: 'solomon_islander', labelEn: 'Solomon Islander', labelAr: 'سليماني' },
  { value: 'tongan', labelEn: 'Tongan', labelAr: 'تونغي' },
  { value: 'tuvaluan', labelEn: 'Tuvaluan', labelAr: 'توفالوي' },
  { value: 'ni_vanuatu', labelEn: 'Ni-Vanuatu', labelAr: 'فانواتي' },
];
