project_id = "lmjivfayjyskriikcyzg"

[functions.create-payment]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.send-viewing-notification]
verify_jwt = false

[functions.send-broadcast-email]
verify_jwt = false
