// Language context for i18n support
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.browseRooms': 'Browse Rooms',
    'nav.findRoom': 'Find a Room',
    'nav.listRoom': 'List Your Room',
    'nav.findRoommate': 'Find a Roommate',
    'nav.findRoommates': 'Find Roommates',
    'nav.howItWorks': 'How It Works',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    'nav.getStarted': 'Get Started',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    
    // Hero
    'hero.verifiedBadge': 'Verified & Safe Roommates',
    'hero.title.part1': 'Find Your Perfect',
    'hero.title.highlight': 'Room',
    'hero.title.part2': 'or',
    'hero.title.highlight2': 'Roommate',
    'hero.title.part3': 'in Egypt',
    'hero.subtitle': 'Sakanak connects you with verified, compatible roommates and quality rooms. No brokers. No scams. Just trusted connections.',
    'hero.cta.findRoom': 'Find a Room',
    'hero.cta.listRoom': 'List Your Room',
    'hero.badge.verified': 'Verified Users Only',
    'hero.badge.secure': 'Secure Payments',
    'hero.badge.support': '24/7 Support',
    'hero.badge.verified100': '100% Verified',
    'hero.stats.verified': 'ID Verified Users',
    'hero.stats.members': '10,000+ Members',
    'hero.stats.listings': '5,000+ Listings',
    'hero.card.title': 'Modern Room in Maadi',
    'hero.card.price': 'EGP 3,500/month',
    
    // Room Card & Rooms
    'room.featured': 'Featured',
    'room.perMonth': '/month',
    'room.verified': 'Verified',
    'rooms.browseTitle': 'Find Your Perfect Room',
    'rooms.browseSubtitle': 'Browse verified rooms in cities across Egypt',
    'rooms.searchPlaceholder': 'Search by city, area, or title...',
    'rooms.resultsFound': 'rooms found',
    'rooms.noResults': 'No rooms found',
    'rooms.noResultsHint': 'Try adjusting your filters or search query',
    'rooms.featured': 'Featured',
    'rooms.verified': 'Verified',
    'rooms.month': 'month',
    'rooms.privateRoom': 'Private Room',
    'rooms.sharedRoom': 'Shared Room',
    'rooms.studio': 'Studio',
    'rooms.apartment': 'Apartment',
    'rooms.filters.title': 'Filters',
    'rooms.filters.city': 'City',
    'rooms.filters.allCities': 'All Cities',
    'rooms.filters.budget': 'Budget (EGP/month)',
    'rooms.filters.min': 'Min',
    'rooms.filters.max': 'Max',
    'rooms.filters.roomType': 'Room Type',
    'rooms.filters.allTypes': 'All Types',
    'rooms.filters.gender': 'Preferred Gender',
    'rooms.filters.any': 'Any',
    'rooms.filters.allGenders': 'All Genders',
    'rooms.filters.allowsSmoking': 'Smoking Allowed',
    'rooms.filters.allowsPets': 'Pets Allowed',
    'rooms.filters.clear': 'Clear Filters',
    
    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Real stories from people who found their perfect match on Sakanak',
    
    // Features
    'features.title': 'Why Choose Sakanak?',
    'features.verified.title': 'Verified Users',
    'features.verified.desc': 'All users go through ID verification for your safety',
    'features.matching.title': 'Smart Matching',
    'features.matching.desc': 'Our algorithm finds compatible roommates based on your preferences',
    'features.secure.title': 'Secure Payments',
    'features.secure.desc': 'Protected escrow payments - your money is safe until you move in',
    'features.gender.title': 'Gender-Safe',
    'features.gender.desc': 'Strict gender filtering ensures comfortable living arrangements',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.step1.title': 'Create Profile',
    'howItWorks.step1.desc': 'Sign up and verify your identity',
    'howItWorks.step2.title': 'Browse Listings',
    'howItWorks.step2.desc': 'Find rooms or roommates that match your preferences',
    'howItWorks.step3.title': 'Connect Safely',
    'howItWorks.step3.desc': 'Chat with verified users through our secure platform',
    'howItWorks.step4.title': 'Move In',
    'howItWorks.step4.desc': 'Complete secure payment and start your new chapter',
    
    // CTA Section
    'cta.title': 'Ready to Find Your Perfect Place?',
    'cta.subtitle': 'Join thousands of verified users already on Sakanak',
    'cta.button': 'Get Started Free',
    
    // Footer
    'footer.description': 'The trusted platform for finding rooms and roommates in Egypt.',
    'footer.quickLinks': 'Quick Links',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.safety': 'Safety Tips',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.rights': 'All rights reserved.',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccountTitle': 'Create Your Account',
    'auth.loginSubtitle': 'Sign in to continue to Sakanak',
    'auth.signupSubtitle': 'Join thousands of verified users',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.email': 'Email Address',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.gender': 'Gender',
    'auth.genderNote': 'This cannot be changed later and is used for matching',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign up',
    'auth.signInLink': 'Sign in',
    'auth.termsText': 'By creating an account, you agree to our',
    'auth.termsLink': 'Terms & Conditions',
    'auth.and': 'and',
    'auth.privacyLink': 'Privacy Policy',
    'auth.brandTitle': 'Find Your Perfect Room or Roommate in Egypt',
    'auth.brandSubtitle': 'Join the trusted community of verified users looking for safe, compatible living spaces.',
    'auth.feature1': 'ID Verified Users Only',
    'auth.feature2': '5,000+ Quality Listings',
    'auth.error.invalidCredentials': 'Invalid email or password. Please try again.',
    'auth.error.emailNotConfirmed': 'Please verify your email address before signing in.',
    'auth.error.alreadyRegistered': 'This email is already registered. Please sign in instead.',
    'auth.success.checkEmail': 'Account created! Please check your email to verify your account.',
    'auth.or': 'or',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.nationality': 'Nationality',
    'auth.selectNationality': 'Select your nationality',

    // Profile
    'profile.edit': 'Edit Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.updateError': 'Failed to update profile',
    'profile.verified': 'Verified',
    'profile.pending': 'Pending Verification',
    'profile.rejected': 'Verification Rejected',
    'profile.unverified': 'Not Verified',
    'profile.phone': 'Phone Number',
    'profile.whatsapp': 'WhatsApp',
    'profile.nationality': 'Nationality',
    'profile.occupation': 'Occupation',
    'profile.about': 'About Me',
    'profile.aboutPlaceholder': 'Tell others about yourself, your lifestyle, and what you are looking for...',
    'profile.lookingFor': 'Looking For',
    'profile.lookingForPlaceholder': 'e.g., Room near downtown, quiet roommate...',
    'profile.isSmoker': 'I smoke',
    'profile.hasPets': 'I have pets',
    'profile.petType': 'Pet Type',
    'profile.petTypePlaceholder': 'e.g., Cat, Dog...',
    'profile.smoker': 'Smoker',
    'profile.myListings': 'My Listings',
    'profile.savedRooms': 'Saved Rooms',
    'profile.addListing': 'Add Listing',
    'profile.noListings': 'You have not listed any rooms yet',
    'profile.noSaved': 'You have not saved any rooms yet',
    'profile.browseRooms': 'Browse Rooms',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',

    // Room Form
    'rooms.form.title': 'List Your Room',
    'rooms.form.subtitle': 'Fill in the details to list your room and find the perfect roommate',
    'rooms.form.loginRequired': 'Please sign in to list a room',
    'rooms.form.verificationRequired': 'You must be verified to list a room',
    'rooms.form.verificationNotice': 'Your account must be verified before you can list rooms. Please complete verification.',
    'rooms.form.verifiedNotice': 'You are verified and can list rooms!',
    'rooms.form.basicInfo': 'Basic Information',
    'rooms.form.basicInfoDesc': 'Provide essential details about your room',
    'rooms.form.roomTitle': 'Title',
    'rooms.form.roomTitlePlaceholder': 'e.g., Modern Private Room in Maadi',
    'rooms.form.description': 'Description',
    'rooms.form.descriptionPlaceholder': 'Describe your room, the apartment, and neighborhood...',
    'rooms.form.roomType': 'Room Type',
    'rooms.form.price': 'Price (EGP/month)',
    'rooms.form.location': 'Location',
    'rooms.form.locationDesc': 'Where is your room located?',
    'rooms.form.city': 'City',
    'rooms.form.selectCity': 'Select a city',
    'rooms.form.area': 'Area',
    'rooms.form.areaPlaceholder': 'e.g., Maadi, Zamalek',
    'rooms.form.address': 'Address',
    'rooms.form.addressPlaceholder': 'Street address (optional)',
    'rooms.form.photos': 'Photos',
    'rooms.form.photosDesc': 'Upload up to 6 photos of your room',
    'rooms.form.addPhoto': 'Add Photo',
    'rooms.form.photosUploaded': 'photos uploaded',
    'rooms.form.invalidImage': 'Please select a valid image file',
    'rooms.form.imageTooLarge': 'Image must be less than 5MB',
    'rooms.form.uploadError': 'Failed to upload image',
    'rooms.form.amenitiesRules': 'Amenities & Rules',
    'rooms.form.amenitiesRulesDesc': 'What does your room offer and what are your house rules?',
    'rooms.form.amenities': 'Amenities',
    'rooms.form.addAmenity': 'Add an amenity...',
    'rooms.form.rules': 'House Rules',
    'rooms.form.addRule': 'Add a rule...',
    'rooms.form.availability': 'Availability & Preferences',
    'rooms.form.availabilityDesc': 'When is the room available and who are you looking for?',
    'rooms.form.availableFrom': 'Available From',
    'rooms.form.pickDate': 'Pick a date',
    'rooms.form.minStay': 'Minimum Stay (months)',
    'rooms.form.maxRoommates': 'Max Roommates',
    'rooms.form.currentRoommates': 'Current Roommates',
    'rooms.form.preferredGender': 'Preferred Gender',
    'rooms.form.allowsSmoking': 'Smoking Allowed',
    'rooms.form.allowsPets': 'Pets Allowed',
    'rooms.form.requiredFields': 'Please fill in all required fields',
    'rooms.form.success': 'Room listed successfully!',
    'rooms.form.error': 'Failed to list room. Please try again.',
    'rooms.form.creating': 'Creating listing...',
    'rooms.form.submit': 'List Room',

    // Verification
    'verification.title': 'Verify Your Identity',
    'verification.subtitle': 'Upload a valid ID document to get verified and unlock all features',
    'verification.whyVerify': 'Verified users can list rooms and are trusted by the community. Your ID is stored securely and reviewed by our team.',
    'verification.verified': 'Identity Verified',
    'verification.verifiedDesc': 'Your account is verified. You can list rooms and access all features.',
    'verification.pending': 'Verification Pending',
    'verification.pendingDesc': 'Your documents are being reviewed. This usually takes 24-48 hours.',
    'verification.rejected': 'Verification Rejected',
    'verification.rejectedDesc': 'Your verification was rejected. Please try again with a clearer document.',
    'verification.reason': 'Reason',
    'verification.documentType': 'Document Type',
    'verification.nationalId': 'National ID',
    'verification.passport': 'Passport',
    'verification.driverLicense': 'Driver License',
    'verification.uploadDocument': 'Upload Document',
    'verification.dragOrClick': 'Click or drag to upload',
    'verification.maxSize': 'Max file size: 10MB (Images or PDF)',
    'verification.clickToChange': 'Click to change file',
    'verification.selectDocument': 'Please select a document to upload',
    'verification.fileTooLarge': 'File is too large. Max size is 10MB.',
    'verification.invalidFileType': 'Invalid file type. Please upload an image or PDF.',
    'verification.submit': 'Submit for Verification',
    'verification.submitting': 'Submitting...',
    'verification.submitSuccess': 'Verification request submitted! We will review it within 24-48 hours.',
    'verification.submitError': 'Failed to submit verification. Please try again.',
    'verification.cancel': 'Cancel Request',
    'verification.cancelSuccess': 'Verification request cancelled.',
    'verification.cancelError': 'Failed to cancel request.',

    // Admin
    'admin.verificationTitle': 'Verification Requests',
    'admin.verificationSubtitle': 'Review and manage user verification requests',
    'admin.allRequests': 'All Requests',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.submittedOn': 'Submitted on',
    'admin.viewDocument': 'View Document',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.approveSuccess': 'User verified successfully!',
    'admin.approveError': 'Failed to approve verification.',
    'admin.rejectSuccess': 'Verification rejected.',
    'admin.rejectError': 'Failed to reject verification.',
    'admin.rejectTitle': 'Reject Verification',
    'admin.rejectReasonLabel': 'Rejection Reason',
    'admin.rejectReasonPlaceholder': 'Explain why the verification was rejected...',
    'admin.rejectReasonRequired': 'Please provide a reason for rejection.',
    'admin.confirmReject': 'Confirm Rejection',
    'admin.noRequests': 'No verification requests',
    'admin.noRequestsHint': 'There are no requests matching your filter.',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'You do not have permission to access this page. Admin privileges are required.',

    // Roommates
    'roommates.title': 'Find a Roommate',
    'roommates.subtitle': 'Browse verified roommates with smart compatibility matching. Find someone who shares your lifestyle preferences.',
    'roommates.searchPlaceholder': 'Search by name, occupation, or interests...',
    'roommates.resultsFound': 'roommates found',
    'roommates.noResults': 'No roommates found',
    'roommates.noResultsHint': 'Try adjusting your filters or check back later. New verified users are added regularly.',
    'roommates.signInNotice': 'Sign in for better matches',
    'roommates.signInDesc': 'Sign in to see personalized compatibility scores based on your profile.',
    'roommates.viewProfile': 'View Profile',
    'roommates.message': 'Message',
    'roommates.compatibility': 'Compatibility',
    'roommates.bestMatch': 'Best Match',
    'roommates.about': 'About',
    'roommates.lookingFor': 'Looking For',
    'roommates.memberSince': 'Member since',
    'roommates.sendMessage': 'Send Message',
    'roommates.interestedConnect': 'Interested in connecting?',
    'roommates.signInToMessage': 'Sign in to message this roommate and see compatibility scores.',
    'roommates.back': 'Back to Roommates',
    'roommates.notFound': 'Roommate not found',
    'roommates.notFoundDesc': 'This profile may not exist or is not available.',
    'roommates.smoker': 'Smoker',
    'roommates.nonSmoker': 'Non-smoker',
    'roommates.hasPets': 'Has pets',

    // Payment Settings
    'payment.settings': 'Payment Settings',
    'payment.settingsDesc': 'Set your insurance deposit and preferred payout method',
    'payment.insurance': 'Insurance/Deposit Amount (EGP)',
    'payment.insuranceDesc': 'This amount will be collected from the seeker as a security deposit',
    'payment.payoutMethod': 'Payout Method',
    'payment.payoutMethodDesc': 'How you want to receive your payment after seeker confirms',
    'payment.instapay': 'Instapay',
    'payment.vodafoneCash': 'Vodafone Cash',
    'payment.fawry': 'Fawry',
    'payment.payoutDetails': 'Payout Details',
    'payment.instapayPlaceholder': 'Enter your Instapay phone number or IPA',
    'payment.vodafonePlaceholder': 'Enter your Vodafone Cash number (e.g., 01xxxxxxxxx)',
    'payment.fawryPlaceholder': 'Enter your Fawry reference or phone number',
    'payment.payoutDetailsDesc': 'This is where we will send your payment. Make sure it is correct!',
    'payment.flowTitle': 'Payment Flow',
    'payment.flowStep1': 'Seeker pays room price + insurance (5% platform fee deducted)',
    'payment.flowStep2': 'When seeker confirms they got the room, you receive your payment',
    'payment.flowStep3': 'Payment sent via your chosen method above',

    // Room Preferences
    'rooms.form.acceptSmokers': 'Accept Smokers?',
    'rooms.form.acceptPets': 'Accept Pets?',
    'rooms.form.yes': 'Yes',
    'rooms.form.no': 'No',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.browseRooms': 'تصفح الغرف',
    'nav.findRoom': 'ابحث عن غرفة',
    'nav.listRoom': 'اعرض غرفتك',
    'nav.findRoommate': 'ابحث عن شريك سكن',
    'nav.findRoommates': 'ابحث عن شركاء سكن',
    'nav.howItWorks': 'كيف يعمل',
    'nav.signIn': 'تسجيل الدخول',
    'nav.signOut': 'تسجيل الخروج',
    'nav.getStarted': 'ابدأ الآن',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    
    // Hero
    'hero.verifiedBadge': 'شركاء سكن موثقون وآمنون',
    'hero.title.part1': 'اعثر على',
    'hero.title.highlight': 'الغرفة',
    'hero.title.part2': 'أو',
    'hero.title.highlight2': 'شريك السكن',
    'hero.title.part3': 'المثالي في مصر',
    'hero.subtitle': 'سكنك يربطك بشركاء سكن موثقين ومتوافقين وغرف عالية الجودة. بدون سماسرة. بدون احتيال. فقط اتصالات موثوقة.',
    'hero.cta.findRoom': 'ابحث عن غرفة',
    'hero.cta.listRoom': 'اعرض غرفتك',
    'hero.badge.verified': 'مستخدمون موثقون فقط',
    'hero.badge.secure': 'دفع آمن',
    'hero.badge.support': 'دعم على مدار الساعة',
    'hero.badge.verified100': '١٠٠٪ موثق',
    'hero.stats.verified': 'مستخدمون موثقون',
    'hero.stats.members': '+١٠,٠٠٠ عضو',
    'hero.stats.listings': '+٥,٠٠٠ إعلان',
    'hero.card.title': 'غرفة حديثة في المعادي',
    'hero.card.price': '٣,٥٠٠ ج.م/شهرياً',
    
    // Room Card & Rooms
    'room.featured': 'مميز',
    'room.perMonth': '/شهرياً',
    'room.verified': 'موثق',
    'rooms.browseTitle': 'ابحث عن غرفتك المثالية',
    'rooms.browseSubtitle': 'تصفح الغرف الموثقة في مدن مصر',
    'rooms.searchPlaceholder': 'ابحث بالمدينة أو المنطقة أو العنوان...',
    'rooms.resultsFound': 'غرفة موجودة',
    'rooms.noResults': 'لم يتم العثور على غرف',
    'rooms.noResultsHint': 'جرب تعديل الفلاتر أو البحث',
    'rooms.featured': 'مميز',
    'rooms.verified': 'موثق',
    'rooms.month': 'شهر',
    'rooms.privateRoom': 'غرفة خاصة',
    'rooms.sharedRoom': 'غرفة مشتركة',
    'rooms.studio': 'ستوديو',
    'rooms.apartment': 'شقة',
    'rooms.filters.title': 'الفلاتر',
    'rooms.filters.city': 'المدينة',
    'rooms.filters.allCities': 'جميع المدن',
    'rooms.filters.budget': 'الميزانية (ج.م/شهر)',
    'rooms.filters.min': 'الحد الأدنى',
    'rooms.filters.max': 'الحد الأقصى',
    'rooms.filters.roomType': 'نوع الغرفة',
    'rooms.filters.allTypes': 'جميع الأنواع',
    'rooms.filters.gender': 'الجنس المفضل',
    'rooms.filters.any': 'أي',
    'rooms.filters.allowsSmoking': 'التدخين مسموح',
    'rooms.filters.allowsPets': 'الحيوانات مسموحة',
    'rooms.filters.clear': 'مسح الفلاتر',
    
    // Testimonials
    'testimonials.title': 'ماذا يقول مستخدمونا',
    'testimonials.subtitle': 'قصص حقيقية من أشخاص وجدوا شريك السكن المثالي على سكنك',
    
    // Features
    'features.title': 'لماذا تختار سكنك؟',
    'features.verified.title': 'مستخدمون موثقون',
    'features.verified.desc': 'جميع المستخدمين يخضعون للتحقق من الهوية لسلامتك',
    'features.matching.title': 'مطابقة ذكية',
    'features.matching.desc': 'خوارزميتنا تجد شركاء سكن متوافقين بناءً على تفضيلاتك',
    'features.secure.title': 'دفع آمن',
    'features.secure.desc': 'مدفوعات محمية - أموالك آمنة حتى تنتقل',
    'features.gender.title': 'أمان جنسي',
    'features.gender.desc': 'فلترة صارمة للجنس تضمن ترتيبات سكن مريحة',
    
    // How It Works
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.step1.title': 'أنشئ ملفك',
    'howItWorks.step1.desc': 'سجل وتحقق من هويتك',
    'howItWorks.step2.title': 'تصفح القوائم',
    'howItWorks.step2.desc': 'ابحث عن غرف أو شركاء سكن يناسبون تفضيلاتك',
    'howItWorks.step3.title': 'تواصل بأمان',
    'howItWorks.step3.desc': 'تحدث مع مستخدمين موثقين عبر منصتنا الآمنة',
    'howItWorks.step4.title': 'انتقل',
    'howItWorks.step4.desc': 'أكمل الدفع الآمن وابدأ فصلك الجديد',
    
    // CTA Section
    'cta.title': 'مستعد للعثور على مكانك المثالي؟',
    'cta.subtitle': 'انضم إلى آلاف المستخدمين الموثقين على سكنك',
    'cta.button': 'ابدأ مجاناً',
    
    // Footer
    'footer.description': 'المنصة الموثوقة للعثور على غرف وشركاء سكن في مصر.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.support': 'الدعم',
    'footer.legal': 'قانوني',
    'footer.contact': 'اتصل بنا',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.safety': 'نصائح السلامة',
    'footer.terms': 'الشروط والأحكام',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.refund': 'سياسة الاسترداد',
    'footer.rights': 'جميع الحقوق محفوظة.',

    // Auth
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.createAccountTitle': 'إنشاء حسابك',
    'auth.loginSubtitle': 'سجل الدخول للمتابعة إلى سكنك',
    'auth.signupSubtitle': 'انضم إلى آلاف المستخدمين الموثقين',
    'auth.fullName': 'الاسم الكامل',
    'auth.fullNamePlaceholder': 'أدخل اسمك الكامل',
    'auth.email': 'البريد الإلكتروني',
    'auth.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.passwordPlaceholder': 'أدخل كلمة المرور',
    'auth.gender': 'الجنس',
    'auth.genderNote': 'لا يمكن تغييره لاحقاً ويستخدم للمطابقة',
    'auth.male': 'ذكر',
    'auth.female': 'أنثى',
    'auth.signIn': 'تسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signUpLink': 'سجل الآن',
    'auth.signInLink': 'تسجيل الدخول',
    'auth.termsText': 'بإنشاء حساب، فإنك توافق على',
    'auth.termsLink': 'الشروط والأحكام',
    'auth.and': 'و',
    'auth.privacyLink': 'سياسة الخصوصية',
    'auth.brandTitle': 'اعثر على غرفتك أو شريك سكنك المثالي في مصر',
    'auth.brandSubtitle': 'انضم إلى المجتمع الموثوق من المستخدمين الذين يبحثون عن أماكن سكن آمنة ومتوافقة.',
    'auth.feature1': 'مستخدمون موثقون بالهوية فقط',
    'auth.feature2': '+٥,٠٠٠ إعلان عالي الجودة',
    'auth.error.invalidCredentials': 'بريد إلكتروني أو كلمة مرور غير صحيحة. حاول مرة أخرى.',
    'auth.error.emailNotConfirmed': 'يرجى التحقق من بريدك الإلكتروني قبل تسجيل الدخول.',
    'auth.error.alreadyRegistered': 'هذا البريد مسجل بالفعل. يرجى تسجيل الدخول.',
    'auth.success.checkEmail': 'تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني لتفعيل حسابك.',
    'auth.or': 'أو',
    'auth.continueWithGoogle': 'المتابعة مع جوجل',
    'auth.nationality': 'الجنسية',
    'auth.selectNationality': 'اختر جنسيتك',

    // Profile
    'profile.edit': 'تعديل الملف',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.updateSuccess': 'تم تحديث الملف بنجاح',
    'profile.updateError': 'فشل تحديث الملف',
    'profile.verified': 'موثق',
    'profile.pending': 'قيد التحقق',
    'profile.rejected': 'مرفوض',
    'profile.unverified': 'غير موثق',
    'profile.phone': 'رقم الهاتف',
    'profile.whatsapp': 'واتساب',
    'profile.nationality': 'الجنسية',
    'profile.occupation': 'المهنة',
    'profile.about': 'نبذة عني',
    'profile.aboutPlaceholder': 'أخبر الآخرين عن نفسك ونمط حياتك وما تبحث عنه...',
    'profile.lookingFor': 'أبحث عن',
    'profile.lookingForPlaceholder': 'مثال: غرفة قريبة من وسط المدينة، شريك سكن هادئ...',
    'profile.isSmoker': 'أنا مدخن',
    'profile.hasPets': 'لدي حيوانات أليفة',
    'profile.petType': 'نوع الحيوان',
    'profile.petTypePlaceholder': 'مثال: قطة، كلب...',
    'profile.smoker': 'مدخن',
    'profile.myListings': 'إعلاناتي',
    'profile.savedRooms': 'الغرف المحفوظة',
    'profile.addListing': 'إضافة إعلان',
    'profile.noListings': 'لم تضف أي غرف بعد',
    'profile.noSaved': 'لم تحفظ أي غرف بعد',
    'profile.browseRooms': 'تصفح الغرف',

    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.loading': 'جاري التحميل...',

    // Room Form
    'rooms.form.title': 'أضف غرفتك',
    'rooms.form.subtitle': 'أدخل تفاصيل غرفتك للعثور على شريك السكن المثالي',
    'rooms.form.loginRequired': 'يرجى تسجيل الدخول لإضافة غرفة',
    'rooms.form.verificationRequired': 'يجب أن تكون موثقاً لإضافة غرفة',
    'rooms.form.verificationNotice': 'يجب التحقق من حسابك قبل إضافة غرف. يرجى إكمال التحقق.',
    'rooms.form.verifiedNotice': 'أنت موثق ويمكنك إضافة غرف!',
    'rooms.form.basicInfo': 'معلومات أساسية',
    'rooms.form.basicInfoDesc': 'أدخل التفاصيل الأساسية عن غرفتك',
    'rooms.form.roomTitle': 'العنوان',
    'rooms.form.roomTitlePlaceholder': 'مثال: غرفة خاصة حديثة في المعادي',
    'rooms.form.description': 'الوصف',
    'rooms.form.descriptionPlaceholder': 'صف غرفتك والشقة والحي...',
    'rooms.form.roomType': 'نوع الغرفة',
    'rooms.form.price': 'السعر (ج.م/شهر)',
    'rooms.form.location': 'الموقع',
    'rooms.form.locationDesc': 'أين تقع غرفتك؟',
    'rooms.form.city': 'المدينة',
    'rooms.form.selectCity': 'اختر مدينة',
    'rooms.form.area': 'المنطقة',
    'rooms.form.areaPlaceholder': 'مثال: المعادي، الزمالك',
    'rooms.form.address': 'العنوان',
    'rooms.form.addressPlaceholder': 'عنوان الشارع (اختياري)',
    'rooms.form.photos': 'الصور',
    'rooms.form.photosDesc': 'ارفع حتى ٦ صور لغرفتك',
    'rooms.form.addPhoto': 'إضافة صورة',
    'rooms.form.photosUploaded': 'صور مرفوعة',
    'rooms.form.invalidImage': 'يرجى اختيار ملف صورة صالح',
    'rooms.form.imageTooLarge': 'يجب أن تكون الصورة أقل من ٥ ميجابايت',
    'rooms.form.uploadError': 'فشل رفع الصورة',
    'rooms.form.amenitiesRules': 'المرافق والقواعد',
    'rooms.form.amenitiesRulesDesc': 'ماذا توفر غرفتك وما هي قواعد المنزل؟',
    'rooms.form.amenities': 'المرافق',
    'rooms.form.addAmenity': 'أضف مرفق...',
    'rooms.form.rules': 'قواعد المنزل',
    'rooms.form.addRule': 'أضف قاعدة...',
    'rooms.form.availability': 'التوفر والتفضيلات',
    'rooms.form.availabilityDesc': 'متى تتوفر الغرفة ومن تبحث عنه؟',
    'rooms.form.availableFrom': 'متاح من',
    'rooms.form.pickDate': 'اختر تاريخ',
    'rooms.form.minStay': 'الحد الأدنى للإقامة (أشهر)',
    'rooms.form.maxRoommates': 'أقصى عدد شركاء السكن',
    'rooms.form.currentRoommates': 'شركاء السكن الحاليون',
    'rooms.form.preferredGender': 'الجنس المفضل',
    'rooms.form.allowsSmoking': 'التدخين مسموح',
    'rooms.form.allowsPets': 'الحيوانات مسموحة',
    'rooms.form.requiredFields': 'يرجى ملء جميع الحقول المطلوبة',
    'rooms.form.success': 'تم إضافة الغرفة بنجاح!',
    'rooms.form.error': 'فشل إضافة الغرفة. حاول مرة أخرى.',
    'rooms.form.creating': 'جاري إنشاء الإعلان...',
    'rooms.form.submit': 'إضافة الغرفة',

    // Verification
    'verification.title': 'تحقق من هويتك',
    'verification.subtitle': 'ارفع وثيقة هوية صالحة للتحقق وفتح جميع الميزات',
    'verification.whyVerify': 'المستخدمون الموثقون يمكنهم إضافة غرف وموثوق بهم من المجتمع. يتم تخزين هويتك بشكل آمن ومراجعتها من قبل فريقنا.',
    'verification.verified': 'تم التحقق من الهوية',
    'verification.verifiedDesc': 'حسابك موثق. يمكنك إضافة غرف والوصول لجميع الميزات.',
    'verification.pending': 'التحقق قيد المراجعة',
    'verification.pendingDesc': 'يتم مراجعة وثائقك. يستغرق هذا عادة ٢٤-٤٨ ساعة.',
    'verification.rejected': 'تم رفض التحقق',
    'verification.rejectedDesc': 'تم رفض طلب التحقق. يرجى المحاولة مرة أخرى بوثيقة أوضح.',
    'verification.reason': 'السبب',
    'verification.documentType': 'نوع الوثيقة',
    'verification.nationalId': 'بطاقة الهوية الوطنية',
    'verification.passport': 'جواز السفر',
    'verification.driverLicense': 'رخصة القيادة',
    'verification.uploadDocument': 'ارفع الوثيقة',
    'verification.dragOrClick': 'انقر أو اسحب للرفع',
    'verification.maxSize': 'الحجم الأقصى: ١٠ ميجابايت (صور أو PDF)',
    'verification.clickToChange': 'انقر لتغيير الملف',
    'verification.selectDocument': 'يرجى اختيار وثيقة للرفع',
    'verification.fileTooLarge': 'الملف كبير جداً. الحجم الأقصى ١٠ ميجابايت.',
    'verification.invalidFileType': 'نوع ملف غير صالح. يرجى رفع صورة أو PDF.',
    'verification.submit': 'إرسال للتحقق',
    'verification.submitting': 'جاري الإرسال...',
    'verification.submitSuccess': 'تم إرسال طلب التحقق! سنراجعه خلال ٢٤-٤٨ ساعة.',
    'verification.submitError': 'فشل إرسال التحقق. يرجى المحاولة مرة أخرى.',
    'verification.cancel': 'إلغاء الطلب',
    'verification.cancelSuccess': 'تم إلغاء طلب التحقق.',
    'verification.cancelError': 'فشل إلغاء الطلب.',

    // Admin
    'admin.verificationTitle': 'طلبات التحقق',
    'admin.verificationSubtitle': 'مراجعة وإدارة طلبات تحقق المستخدمين',
    'admin.allRequests': 'جميع الطلبات',
    'admin.pending': 'قيد الانتظار',
    'admin.approved': 'موافق عليه',
    'admin.rejected': 'مرفوض',
    'admin.submittedOn': 'أرسل في',
    'admin.viewDocument': 'عرض الوثيقة',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.approveSuccess': 'تم التحقق من المستخدم بنجاح!',
    'admin.approveError': 'فشل الموافقة على التحقق.',
    'admin.rejectSuccess': 'تم رفض التحقق.',
    'admin.rejectError': 'فشل رفض التحقق.',
    'admin.rejectTitle': 'رفض التحقق',
    'admin.rejectReasonLabel': 'سبب الرفض',
    'admin.rejectReasonPlaceholder': 'اشرح سبب رفض التحقق...',
    'admin.rejectReasonRequired': 'يرجى تقديم سبب للرفض.',
    'admin.confirmReject': 'تأكيد الرفض',
    'admin.noRequests': 'لا توجد طلبات تحقق',
    'admin.noRequestsHint': 'لا توجد طلبات تطابق الفلتر الخاص بك.',
    'admin.accessDenied': 'الوصول مرفوض',
    'admin.accessDeniedDesc': 'ليس لديك صلاحية للوصول لهذه الصفحة. صلاحيات المسؤول مطلوبة.',

    // Roommates
    'roommates.title': 'ابحث عن شريك سكن',
    'roommates.subtitle': 'تصفح شركاء السكن الموثقين مع المطابقة الذكية. اعثر على شخص يشاركك تفضيلات نمط الحياة.',
    'roommates.searchPlaceholder': 'ابحث بالاسم أو المهنة أو الاهتمامات...',
    'roommates.resultsFound': 'شريك سكن موجود',
    'roommates.noResults': 'لم يتم العثور على شركاء سكن',
    'roommates.noResultsHint': 'جرب تعديل الفلاتر أو عد لاحقاً. يتم إضافة مستخدمين موثقين جدد بانتظام.',
    'roommates.signInNotice': 'سجل الدخول لمطابقات أفضل',
    'roommates.signInDesc': 'سجل الدخول لرؤية نسب التوافق المخصصة بناءً على ملفك الشخصي.',
    'roommates.viewProfile': 'عرض الملف',
    'roommates.message': 'رسالة',
    'roommates.compatibility': 'التوافق',
    'roommates.bestMatch': 'أفضل تطابق',
    'roommates.about': 'نبذة',
    'roommates.lookingFor': 'يبحث عن',
    'roommates.memberSince': 'عضو منذ',
    'roommates.sendMessage': 'إرسال رسالة',
    'roommates.interestedConnect': 'مهتم بالتواصل؟',
    'roommates.signInToMessage': 'سجل الدخول لمراسلة هذا الشريك ورؤية نسب التوافق.',
    'roommates.back': 'العودة لشركاء السكن',
    'roommates.notFound': 'شريك السكن غير موجود',
    'roommates.notFoundDesc': 'هذا الملف قد لا يكون موجوداً أو غير متاح.',
    'roommates.smoker': 'مدخن',
    'roommates.nonSmoker': 'غير مدخن',
    'roommates.hasPets': 'لديه حيوانات أليفة',

    // Payment Settings
    'payment.settings': 'إعدادات الدفع',
    'payment.settingsDesc': 'حدد مبلغ التأمين وطريقة الاستلام المفضلة',
    'payment.insurance': 'مبلغ التأمين/الضمان (ج.م)',
    'payment.insuranceDesc': 'سيتم تحصيل هذا المبلغ من الباحث كوديعة ضمان',
    'payment.payoutMethod': 'طريقة الاستلام',
    'payment.payoutMethodDesc': 'كيف تريد استلام دفعتك بعد تأكيد الباحث',
    'payment.instapay': 'انستاباي',
    'payment.vodafoneCash': 'فودافون كاش',
    'payment.fawry': 'فوري',
    'payment.payoutDetails': 'تفاصيل الاستلام',
    'payment.instapayPlaceholder': 'أدخل رقم هاتف انستاباي أو IPA',
    'payment.vodafonePlaceholder': 'أدخل رقم فودافون كاش (مثل: 01xxxxxxxxx)',
    'payment.fawryPlaceholder': 'أدخل رقم فوري المرجعي أو رقم الهاتف',
    'payment.payoutDetailsDesc': 'هنا سنرسل دفعتك. تأكد من صحته!',
    'payment.flowTitle': 'مسار الدفع',
    'payment.flowStep1': 'الباحث يدفع سعر الغرفة + التأمين (خصم ٥٪ رسوم المنصة)',
    'payment.flowStep2': 'عندما يؤكد الباحث استلامه الغرفة، تستلم دفعتك',
    'payment.flowStep3': 'يتم إرسال الدفعة بالطريقة المختارة أعلاه',

    // Room Preferences
    'rooms.form.acceptSmokers': 'تقبل المدخنين؟',
    'rooms.form.acceptPets': 'تقبل الحيوانات الأليفة؟',
    'rooms.form.yes': 'نعم',
    'rooms.form.no': 'لا',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
