// Language context for i18n support
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.browseRooms': 'Browse Places',
    'nav.findRoom': 'Find a Place',
    'nav.listRoom': 'List Your Place',
    'nav.findRoommate': 'Find a Roommate',
    'nav.findRoommates': 'Find Roommates',
    'nav.howItWorks': 'How It Works',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    'nav.getStarted': 'Get Started',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    
    // Hero
    'hero.verifiedBadge': 'Verified & Safe Roommates',
    'hero.title.part1': 'Find Your Perfect',
    'hero.title.highlight': 'Room',
    'hero.title.part2': 'or',
    'hero.title.highlight2': 'Roommate',
    'hero.title.part3': 'in Egypt',
    'hero.subtitle': 'Sakanak connects you with verified, compatible roommates and quality rooms. No brokers. No scams. Just trusted connections.',
    'hero.cta.findRoom': 'Find a Place',
    'hero.cta.listRoom': 'List Your Place',
    'hero.badge.verified': 'Verified Users Only',
    'hero.badge.secure': 'Secure Payments',
    'hero.badge.support': '24/7 Support',
    'hero.badge.verified100': '100% Verified',
    'hero.stats.verified': 'ID Verified Users',
    'hero.stats.members': '10,000+ Members',
    'hero.stats.listings': '5,000+ Listings',
    'hero.card.title': 'Modern Room in Maadi',
    'hero.card.price': 'EGP 3,500/month',
    
    // Room Card & Rooms
    'room.featured': 'Featured',
    'room.perMonth': '/month',
    'room.verified': 'Verified',
    'rooms.browseTitle': 'Find Your Perfect Place',
    'rooms.browseSubtitle': 'Browse verified places in cities across Egypt',
    'rooms.searchPlaceholder': 'Search by city, area, or title...',
    'rooms.resultsFound': 'places found',
    'rooms.noResults': 'No places found',
    'rooms.noResultsHint': 'Try adjusting your filters or search query',
    'rooms.featured': 'Featured',
    'rooms.verified': 'Verified Listing',
    'rooms.month': 'month',
    'rooms.privateRoom': 'Private Room',
    'rooms.sharedRoom': 'Shared Room',
    'rooms.studio': 'Studio',
    'rooms.apartment': 'Apartment',
    'rooms.filters.title': 'Filters',
    'rooms.filters.city': 'City',
    'rooms.filters.allCities': 'All Cities',
    'rooms.filters.budget': 'Budget (EGP/month)',
    'rooms.filters.min': 'Min',
    'rooms.filters.max': 'Max',
    'rooms.filters.roomType': 'Room Type',
    'rooms.filters.allTypes': 'All Types',
    'rooms.filters.gender': 'Preferred Gender',
    'rooms.filters.any': 'Any',
    'rooms.filters.allGenders': 'All Genders',
    'rooms.filters.allowsSmoking': 'Smoking Allowed',
    'rooms.filters.allowsPets': 'Pets Allowed',
    'rooms.filters.clear': 'Clear Filters',
    'rooms.filters.done': 'Done',
     'rooms.delete': 'Delete',
     'rooms.deleteConfirmTitle': 'Delete Listing',
     'rooms.deleteConfirmDesc': 'Are you sure you want to delete this listing? This action cannot be undone.',
     'rooms.deleteSuccess': 'Listing deleted successfully',
     'rooms.deleteError': 'Failed to delete listing',

    // Room Details
    'roomDetails.backToRooms': 'Back to Listings',
    'roomDetails.notFound': 'Listing Not Found',
    'roomDetails.notFoundDesc': 'This listing may no longer be available.',
    'roomDetails.browseRooms': 'Browse Places',
    'roomDetails.featured': 'Featured',
    'roomDetails.verifiedOwner': 'Verified Listing',
    'roomDetails.malesOnly': 'Males Only',
    'roomDetails.femalesOnly': 'Females Only',
    'roomDetails.anyGender': 'Any Gender',
    'roomDetails.perMonth': 'per month',
    'roomDetails.roommates': 'roommates',
    'roomDetails.minMonths': 'min months',
    'roomDetails.deposit': 'deposit',
    'roomDetails.none': 'None',
    'roomDetails.aboutRoom': 'About This Room',
    'roomDetails.amenities': 'Amenities',
    'roomDetails.houseRules': 'House Rules',
    'roomDetails.smokingAllowed': 'Smoking allowed',
    'roomDetails.noSmoking': 'No smoking',
    'roomDetails.petsAllowed': 'Pets allowed',
    'roomDetails.noPets': 'No pets',
    'roomDetails.listedBy': 'Listed By',
    'roomDetails.roomOwner': 'Room Owner',
    'roomDetails.message': 'Message',
    'roomDetails.messageFailed': 'Failed to start conversation. Please verify your account.',
    'roomDetails.yourListing': 'This is your listing',
    'roomDetails.cantReserveOwn': 'You cannot reserve your own room.',
    'roomDetails.manageListing': 'Manage Listing',
    
    // Reservation Form
    'reservation.title': 'Reserve This Room',
    'reservation.subtitle': 'Secure your spot by making a payment',
    'reservation.checkInDate': 'Check-in Date',
    'reservation.selectDate': 'Select date',
    'reservation.duration': 'Duration (months)',
    'reservation.minStay': 'Minimum stay:',
    'reservation.months': 'months',
    'reservation.priceBreakdown': 'Price Breakdown',
    'reservation.room': 'Room',
    'reservation.month': 'month',
    'reservation.securityDeposit': 'Security Deposit',
    'reservation.platformFee': 'Platform Fee (5%)',
    'reservation.total': 'Total',
    'reservation.protectedBy': 'Protected by Sakanak',
    'reservation.protectedDesc': 'Your payment is secure. The owner will receive the payment only after you confirm you\'ve received the room.',
    'reservation.processing': 'Processing...',
    'reservation.pay': 'Pay',
    'reservation.loginRequired': 'Please login to reserve this room',
    'reservation.created': 'Reservation created! Redirecting to payment...',
    'reservation.failed': 'Failed to create reservation',
    'reservation.roomNotFound': 'Room not found',
    'reservation.currency': 'EGP',
    
    // Messages
    'messages.title': 'Messages',
    'messages.signInRequired': 'Sign in to view messages',
    'messages.signInDesc': 'You need to be logged in to access your conversations',
    'messages.signIn': 'Sign In',
    'messages.allChatsProtected': 'All chats are protected',
    'messages.selectConversation': 'Select a conversation',
    'messages.selectConversationDesc': 'Choose a conversation from the list to start messaging',
    'messages.failedToLoad': 'Failed to load conversations',
    'messages.noConversations': 'No conversations yet',
    'messages.startChatting': 'Start chatting by messaging a room owner',
    'messages.unknownUser': 'Unknown User',
    'messages.noMessagesYet': 'No messages yet',
    'messages.you': 'You',
    'messages.conversationNotFound': 'Conversation not found',
    'messages.protectedNotice': 'Protected by Sakanak - Contact info sharing is blocked for your security',
    'messages.noMessagesStart': 'No messages yet. Start the conversation!',
    'messages.contentFiltered': 'Content filtered',
    'messages.yesterday': 'Yesterday',
    'messages.typeMessage': 'Type a message...',
    'messages.failedToSend': 'Failed to send message',
    
    // Testimonials
    'testimonials.title': 'What Our Users Say',
    'testimonials.subtitle': 'Real stories from people who found their perfect match on Sakanak',
    
    // Features
    'features.title': 'Why Choose Sakanak?',
    'features.verified.title': 'Verified Users',
    'features.verified.desc': 'All users go through ID verification for your safety',
    'features.matching.title': 'Smart Matching',
    'features.matching.desc': 'Our algorithm finds compatible rooms based on your preferences',
    'features.secure.title': '100% Free (Limited Time)',
    'features.secure.desc': 'Completely free to use now! Later, just a 5% fee on the first month — only charged after you move in. If you don\'t, you get a full refund.',
    'features.gender.title': 'Gender-Safe',
    'features.gender.desc': 'Strict gender filtering ensures comfortable living arrangements',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.step1.title': 'Create Profile',
    'howItWorks.step1.desc': 'Sign up and verify your identity',
    'howItWorks.step2.title': 'Browse Listings',
    'howItWorks.step2.desc': 'Find rooms or roommates that match your preferences',
    'howItWorks.step3.title': 'Book a Viewing',
    'howItWorks.step3.desc': 'Schedule a viewing with the host and visit the place in person',
    'howItWorks.step4.title': 'Move In',
    'howItWorks.step4.desc': 'Confirm the deal and start your new chapter — 100% free for now!',
    
    // CTA Section
    'cta.title': 'Ready to Find Your Perfect Place?',
    'cta.subtitle': 'Browse verified rooms and roommates across Egypt — no sign-up needed to explore',
    'cta.button': 'Browse Rooms Now',
    
    // Footer
    'footer.description': 'The trusted platform for finding rooms and roommates in Egypt.',
    'footer.quickLinks': 'Quick Links',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.safety': 'Safety Tips',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.rights': 'All rights reserved.',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccountTitle': 'Create Your Account',
    'auth.loginSubtitle': 'Sign in to continue to Sakanak',
    'auth.signupSubtitle': 'Join thousands of verified users',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.email': 'Email Address',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.gender': 'Gender',
    'auth.genderNote': 'This cannot be changed later and is used for matching',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.signIn': 'Sign In',
    'auth.createAccount': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign up',
    'auth.signInLink': 'Sign in',
    'auth.termsText': 'By creating an account, you agree to our',
    'auth.termsLink': 'Terms & Conditions',
    'auth.and': 'and',
    'auth.privacyLink': 'Privacy Policy',
    'auth.brandTitle': 'Find Your Perfect Room or Roommate in Egypt',
    'auth.brandSubtitle': 'Join the trusted community of verified users looking for safe, compatible living spaces.',
    'auth.feature1': 'ID Verified Users Only',
    'auth.feature2': '100+ Quality Listings',
    'auth.error.invalidCredentials': 'Invalid email or password. Please try again.',
    'auth.error.emailNotConfirmed': 'Please verify your email address before signing in.',
    'auth.error.alreadyRegistered': 'This email is already registered. Please sign in instead.',
    'auth.error.rateLimitExceeded': 'Too many attempts. Please wait a few minutes and try again.',
    'auth.resendEmail': 'Resend verification email',
    'auth.resendEmailSending': 'Sending...',
    'auth.resendEmailSuccess': 'Verification email sent! Please check your inbox.',
    'auth.success.checkEmail': 'Account created! Please check your email to verify your account.',
    'auth.success.checkStudentEmail': 'Student account created! Please check your university email to verify your account. Your student status will be automatically verified.',
    'auth.or': 'or',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.continueWithApple': 'Continue with Apple',
    'auth.joinAsStudent': 'Join as Student',
    'auth.studentSignupTitle': 'Join as Student',
    'auth.studentSignupSubtitle': 'Sign up with your university email to get automatically verified',
    'auth.studentEmail': 'University Email',
    'auth.studentEmailPlaceholder': 'your.name@university.edu.eg',
    'auth.studentEmailError': 'Please use a valid university email (.edu, .edu.eg, .ac, etc.)',
    'auth.backToSignup': 'Back to regular signup',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordSubtitle': 'Enter your email to receive a reset link',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.backToLogin': 'Back to login',
    'auth.resetEmailSent': 'Password reset email sent! Check your inbox.',
    
    // Reset Password Page
    'resetPassword.title': 'Set New Password',
    'resetPassword.subtitle': 'Enter your new password below',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.newPasswordPlaceholder': 'Enter your new password',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.confirmPasswordPlaceholder': 'Confirm your new password',
    'resetPassword.updatePassword': 'Update Password',
    'resetPassword.passwordsMustMatch': 'Passwords must match',
    'resetPassword.success': 'Password updated successfully! Redirecting...',
    'resetPassword.invalidLink': 'Invalid Reset Link',
    'resetPassword.invalidLinkDesc': 'This password reset link is invalid or has expired. Please request a new one.',
    'resetPassword.backToLogin': 'Back to Login',
    
    'auth.nationality': 'Nationality',
    'auth.selectNationality': 'Select your nationality',

    // Profile
    'profile.edit': 'Edit Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.updateError': 'Failed to update profile',
    'profile.verified': 'Verified',
    'profile.pending': 'Pending Verification',
    'profile.rejected': 'Verification Rejected',
    'profile.unverified': 'Not Verified',
    'profile.phone': 'Phone Number',
    'profile.whatsapp': 'WhatsApp',
    'profile.nationality': 'Nationality',
    'profile.occupation': 'Occupation',
    'profile.about': 'About Me',
    'profile.aboutPlaceholder': 'Tell others about yourself, your lifestyle, and what you are looking for...',
    'profile.lookingFor': 'Looking For',
    'profile.lookingForPlaceholder': 'e.g., Room near downtown, quiet roommate...',
    'profile.isSmoker': 'I smoke',
    'profile.hasPets': 'I have pets',
    'profile.petType': 'Pet Type',
    'profile.petTypePlaceholder': 'e.g., Cat, Dog...',
    'profile.smoker': 'Smoker',
    'profile.myListings': 'My Listings',
    'profile.savedRooms': 'Saved Rooms',
    'profile.addListing': 'Add Listing',
    'profile.noListings': 'You have not listed any rooms yet',
    'profile.noSaved': 'You have not saved any rooms yet',
    'profile.browseRooms': 'Browse Rooms',
     'profile.changePassword.title': 'Change Password',
     'profile.changePassword.description': 'Update your password to keep your account secure',
     'profile.changePassword.current': 'Current Password',
     'profile.changePassword.new': 'New Password',
     'profile.changePassword.confirm': 'Confirm New Password',
     'profile.changePassword.requirements': 'Password must be at least 8 characters',
     'profile.changePassword.minLength': 'Password must be at least 8 characters',
     'profile.changePassword.mismatch': 'Passwords do not match',
     'profile.changePassword.samePassword': 'New password must be different from current password',
     'profile.changePassword.match': 'Passwords match',
     'profile.changePassword.submit': 'Update Password',
     'profile.changePassword.success': 'Password updated successfully',
     'profile.changePassword.error': 'Failed to update password',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.unknown': 'Unknown',

    // Room Form
    'rooms.form.title': 'List Your Place',
    'rooms.form.subtitle': 'Fill in the details to list your place and find the perfect roommate',
    'rooms.form.loginRequired': 'Please sign in to list a place',
    'rooms.form.verificationRequired': 'You must be verified to list a place',
    'rooms.form.verificationNotice': 'Your account must be verified before you can list places. Please complete verification.',
    'rooms.form.verifiedNotice': 'You are verified and can list places!',
    'rooms.form.basicInfo': 'Basic Information',
    'rooms.form.basicInfoDesc': 'Provide essential details about your place',
    'rooms.form.roomTitle': 'Title',
    'rooms.form.roomTitlePlaceholder': 'e.g., Modern Private Room in Maadi',
    'rooms.form.description': 'Description',
    'rooms.form.descriptionPlaceholder': 'Describe your place, the apartment, and neighborhood...',
    'rooms.form.roomType': 'Room Type',
    'rooms.form.price': 'Price (EGP/month)',
    'rooms.form.location': 'Location',
    'rooms.form.locationDesc': 'Where is your place located?',
    'rooms.form.city': 'City',
    'rooms.form.selectCity': 'Select a city',
    'rooms.form.area': 'Area',
    'rooms.form.areaPlaceholder': 'e.g., Maadi, Zamalek',
    'rooms.form.address': 'Address',
    'rooms.form.addressPlaceholder': 'Street address',
    'rooms.form.photos': 'Photos',
    'rooms.form.photosDesc': 'Upload up to 6 photos of your place',
    'rooms.form.addPhoto': 'Add Photo',
    'rooms.form.photosUploaded': 'photos uploaded',
    'rooms.form.invalidImage': 'Please select a valid image file',
    'rooms.form.imageTooLarge': 'Image must be less than 5MB',
    'rooms.form.uploadError': 'Failed to upload image',
    'rooms.form.amenitiesRules': 'Amenities & Rules',
    'rooms.form.amenitiesRulesDesc': 'What does your place offer and what are your house rules?',
    'rooms.form.amenities': 'Amenities',
    'rooms.form.addAmenity': 'Add an amenity...',
    'rooms.form.rules': 'House Rules',
    'rooms.form.addRule': 'Add a rule...',
    'rooms.form.availability': 'Availability & Preferences',
    'rooms.form.availabilityDesc': 'When is the place available and who are you looking for?',
    'rooms.form.availableFrom': 'Available From',
    'rooms.form.pickDate': 'Pick a date',
    'rooms.form.minStay': 'Minimum Stay (months)',
    'rooms.form.maxRoommates': 'Max Roommates',
    'rooms.form.currentRoommates': 'Current Roommates',
    'rooms.form.preferredGender': 'Preferred Gender',
    'rooms.form.allowsSmoking': 'Smoking Allowed',
    'rooms.form.allowsPets': 'Pets Allowed',
    'rooms.form.requiredFields': 'Please fill in all required fields',
    'rooms.form.success': 'Place listed successfully!',
    'rooms.form.error': 'Failed to list place. Please try again.',
    'rooms.form.creating': 'Creating listing...',
    'rooms.form.submit': 'List Place',
    'rooms.form.yes': 'Yes',
    'rooms.form.no': 'No',
    'rooms.form.acceptSmokers': 'Smoking Allowed',
    'rooms.form.acceptPets': 'Pets Allowed',
    // New amenity fields
    'rooms.form.amenitiesDesc': 'Select the amenities available in your place',
    'rooms.form.naturalGas': 'Natural Gas',
    'rooms.form.wifi': 'WiFi Available',
    'rooms.form.elevator': 'Elevator',
    'rooms.form.balcony': 'Balcony',
    'rooms.form.doorman': 'Doorman/Security',
    'rooms.form.ac': 'Air Conditioning',
    'rooms.form.waterHeater': 'Water Heater',
    // House rules
    'rooms.form.houseRules': 'House Rules',
    'rooms.form.houseRulesDesc': 'Set the rules for your place',
    'rooms.form.allowsVisits': 'Visits Allowed',
    // Capacity fields
    'rooms.form.capacity': 'Capacity',
    'rooms.form.capacityDesc': 'Set the capacity and current occupancy',
    'rooms.form.totalBedrooms': 'Total Bedrooms',
    'rooms.form.totalBedroomsHint': 'Total number of bedrooms in the apartment',
    'rooms.form.currentOccupants': 'Current Occupants',
    'rooms.form.currentOccupantsHint': 'Number of people currently living there',
    // Location link
    'rooms.form.locationLink': 'Location Link',
    'rooms.form.locationLinkPlaceholder': 'Paste Google Maps or Apple Maps link',
    'rooms.form.locationLinkHint': 'Share a map link so viewers can easily find the location',
    'rooms.form.locationPrivacyNotice': 'Your exact location is private and will only be shared with tenants after you confirm a viewing appointment.',

    // Verification
    'verification.title': 'Verify Your Identity',
    'verification.subtitle': 'Upload a valid ID document to get verified and unlock all features',
    'verification.whyVerify': 'Verified users can list rooms and are trusted by the community. Your ID is stored securely and reviewed by our team.',
    'verification.verified': 'Identity Verified',
    'verification.verifiedDesc': 'Your account is verified. You can list rooms and access all features.',
    'verification.pending': 'Verification Pending',
    'verification.pendingDesc': 'Your documents are being reviewed. This usually takes 24-48 hours.',
    'verification.rejected': 'Verification Rejected',
    'verification.rejectedDesc': 'Your verification was rejected. Please try again with a clearer document.',
    'verification.reason': 'Reason',
    'verification.documentType': 'Document Type',
    'verification.nationalId': 'National ID',
    'verification.passport': 'Passport',
    'verification.driverLicense': 'Driver License',
    'verification.uploadDocument': 'Upload Document',
    'verification.dragOrClick': 'Click or drag to upload',
    'verification.maxSize': 'Max file size: 10MB (Images or PDF)',
    'verification.clickToChange': 'Click to change file',
    'verification.selectDocument': 'Please select a document to upload',
    'verification.fileTooLarge': 'File is too large. Max size is 10MB.',
    'verification.invalidFileType': 'Invalid file type. Please upload an image or PDF.',
    'verification.submit': 'Submit for Verification',
    'verification.submitting': 'Submitting...',
    'verification.submitSuccess': 'Verification request submitted! We will review it within 24-48 hours.',
    'verification.submitError': 'Failed to submit verification. Please try again.',
    'verification.cancel': 'Cancel Request',
    'verification.cancelSuccess': 'Verification request cancelled.',
    'verification.cancelError': 'Failed to cancel request.',
     'verification.frontPhoto': 'Front of ID',
     'verification.backPhoto': 'Back of ID',
     'verification.uploadFront': 'Upload front side of your ID',
     'verification.uploadBack': 'Upload back side of your ID',
     'verification.selectBothDocuments': 'Please upload both front and back photos of your ID',

    // Admin
    'admin.verificationTitle': 'Verification Requests',
    'admin.verificationSubtitle': 'Review and manage user verification requests',
    'admin.allRequests': 'All Requests',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.submittedOn': 'Submitted on',
    'admin.viewDocument': 'View Document',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.approveSuccess': 'User verified successfully!',
    'admin.approveError': 'Failed to approve verification.',
    'admin.rejectSuccess': 'Verification rejected.',
    'admin.rejectError': 'Failed to reject verification.',
    'admin.rejectTitle': 'Reject Verification',
    'admin.rejectReasonLabel': 'Rejection Reason',
    'admin.rejectReasonPlaceholder': 'Explain why the verification was rejected...',
    'admin.rejectReasonRequired': 'Please provide a reason for rejection.',
    'admin.confirmReject': 'Confirm Rejection',
    'admin.noRequests': 'No verification requests',
    'admin.noRequestsHint': 'There are no requests matching your filter.',
    'admin.accessDenied': 'Access Denied',
    'admin.accessDeniedDesc': 'You do not have permission to access this page. Admin privileges are required.',
     'admin.viewFront': 'View Front',
     'admin.viewBack': 'View Back',

    // Roommates
    'roommates.title': 'Find a Roommate',
    'roommates.subtitle': 'Browse verified roommates with smart compatibility matching. Find someone who shares your lifestyle preferences.',
    'roommates.searchPlaceholder': 'Search by name, occupation, or interests...',
    'roommates.resultsFound': 'roommates found',
    'roommates.noResults': 'No roommates found',
    'roommates.noResultsHint': 'Try adjusting your filters or check back later. New verified users are added regularly.',
    'roommates.signInNotice': 'Sign in for better matches',
    'roommates.signInDesc': 'Sign in to see personalized compatibility scores based on your profile.',
    'roommates.viewProfile': 'View Profile',
    'roommates.message': 'Message',
    'roommates.compatibility': 'Compatibility',
    'roommates.bestMatch': 'Best Match',
    'roommates.about': 'About',
    'roommates.lookingFor': 'Looking For',
    'roommates.memberSince': 'Member since',
    'roommates.sendMessage': 'Send Message',
    'roommates.interestedConnect': 'Interested in connecting?',
    'roommates.signInToMessage': 'Sign in to message this roommate and see compatibility scores.',
    'roommates.back': 'Back to Roommates',
    'roommates.notFound': 'Roommate not found',
    'roommates.notFoundDesc': 'This profile may not exist or is not available.',
    'roommates.smoker': 'Smoker',
    'roommates.nonSmoker': 'Non-smoker',
    'roommates.hasPets': 'Has pets',
    'roommates.filters.search': 'Search',
    'roommates.filters.searchPlaceholder': 'Search by name, about, or occupation...',
    'roommates.filters.occupation': 'Occupation',
    'roommates.filters.occupationPlaceholder': 'e.g., Student, Engineer...',
    'roommates.filters.smoker': 'Smoker',
    'roommates.filters.hasPets': 'Has Pets',
    'roommates.filters.clear': 'Clear Filters',
    'roommates.filters.title': 'Filters',

    // Payment Settings
    'payment.settings': 'Payment Settings',
    'payment.settingsDesc': 'Set your insurance deposit and preferred payout method',
    'payment.insurance': 'Insurance/Deposit Amount (EGP)',
    'payment.insuranceDesc': 'This amount will be collected from the seeker as a security deposit',
    'payment.payoutMethod': 'Payout Method',
    'payment.payoutMethodDesc': 'How you want to receive your payment after seeker confirms',
    'payment.instapay': 'Instapay',
    'payment.vodafoneCash': 'Vodafone Cash',
    'payment.fawry': 'Fawry',
    'payment.payoutDetails': 'Payout Details',
    'payment.instapayPlaceholder': 'Enter your Instapay phone number or IPA',
    'payment.vodafonePlaceholder': 'Enter your Vodafone Cash number (e.g., 01xxxxxxxxx)',
    'payment.fawryPlaceholder': 'Enter your Fawry reference or phone number',
    'payment.payoutDetailsDesc': 'This is where we will send your payment. Make sure it is correct!',
    'payment.flowTitle': 'Payment Flow',
    'payment.flowStep1': 'Seeker pays room price + insurance (5% platform fee deducted)',
    'payment.flowStep2': 'When seeker confirms they got the room, you receive your payment',
    'payment.flowStep3': 'Payment sent via your chosen method above',


    // Viewing
    'viewing.bookTitle': 'Book a Viewing',
    'viewing.selectDate': 'Select Date',
    'viewing.pickDate': 'Pick a date',
    'viewing.preferredTime': 'Preferred Time',
    'viewing.selectTime': 'Select',
    'viewing.duration': 'Duration',
    'viewing.message': 'Message (Optional)',
    'viewing.messagePlaceholder': 'Any specific questions or requests...',
    'viewing.messageNote': 'No phone numbers, emails, or links allowed',
    'viewing.noContactInfo': 'Contact information (phone, email, links) is not allowed',
    'viewing.sendRequest': 'Send Viewing Request',
    'viewing.verificationRequired': 'You need to verify your identity before booking viewings. Please complete verification in your profile.',

    // My Viewings Page
    'viewings.myViewings': 'My Viewings',
    'viewings.manageViewings': 'Manage your scheduled property viewings',
    'viewings.asTenant': 'As Tenant',
    'viewings.asLandlord': 'As Landlord',
    'viewings.active': 'Active Viewings',
    'viewings.past': 'Past Viewings',
    'viewings.noViewings': 'No viewings yet',
    'viewings.noViewingsDescription': 'Browse rooms and book a viewing to get started.',
    'viewings.browseRooms': 'Browse Rooms',
    'viewings.pendingRequests': 'Pending Requests',
    'viewings.scheduled': 'Scheduled Viewings',
    'viewings.noRequests': 'No viewing requests',
    'viewings.noRequestsDescription': 'When tenants request viewings for your rooms, they will appear here.',
    'viewings.atProperty': 'At the property?',
    'viewings.markArrivedDescription': 'Mark yourself as arrived to unlock the rental confirmation options.',
    'viewings.imHere': "I'm Here",
    'viewings.viewing': 'Viewing',

    // Viewing Card
    'viewing.landlord': 'Landlord',
    'viewing.tenant': 'Tenant',
    'viewing.proposedTime': 'Proposed Time',
    'viewing.confirmedTime': 'Confirmed Time',
    'viewing.newTimeProposed': 'New Time Proposed',
    'viewing.originalTime': 'Original',
    'viewing.tenantMessage': 'Tenant Message',
    'viewing.landlordResponse': 'Landlord Response',
    'viewing.locationShared': 'Location shared via chat',
    'viewing.confirm': 'Confirm',
    'viewing.proposeNewTime': 'New Time',
    'viewing.shareLocation': 'Share Location',
    'viewing.acceptTime': 'Accept Time',
    'viewing.cancel': 'Cancel',
    'viewing.confirmRental': 'Confirm Rental',
    'viewing.decline': 'Decline',
    'viewing.chat': 'Chat',
    'viewing.chatLocked': 'Chat Locked',
    'viewing.chatUnlocksAfterConfirm': 'Chat will unlock after the viewing is confirmed by both parties',
    'viewing.chatWithLandlord': 'Chat with Landlord',
    'viewing.chatWithTenant': 'Chat with Tenant',
    'viewing.startChatting': 'Start chatting to coordinate your viewing',
    'viewing.noPhoneEmail': 'Phone numbers and emails are not allowed',

    // Q&A
    'qa.title': 'Questions & Answers',
    'qa.askPlaceholder': 'Ask a question about this listing...',
    'qa.verifyFirst': 'Verify your account to ask questions',
    'qa.askButton': 'Ask Question',
    'qa.ownerAnswer': 'Owner',
    'qa.answerPlaceholder': 'Write your answer...',
    'qa.postAnswer': 'Post Answer',
    'qa.answerButton': 'Answer',
    'qa.awaitingAnswer': 'Awaiting owner response',
    'qa.noQuestions': 'No questions yet. Be the first to ask!',

    // Counter Propose Dialog
    'viewing.proposeNewTimeTitle': 'Propose New Time',
    'viewing.counterProposeDescription': 'Suggest an alternative time that works better for you.',
    'viewing.originalRequest': 'Original Request',
    'viewing.newDate': 'New Date',
    'viewing.responseMessage': 'Message (Optional)',
    'viewing.responseMessagePlaceholder': 'Explain why this time works better...',
    'viewing.sendProposal': 'Send Proposal',
    'viewing.alreadyRequested': 'You already have an active viewing request for this room',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.browseRooms': 'تصفح الأماكن',
    'nav.findRoom': 'ابحث عن سكن',
    'nav.listRoom': 'اعرض سكنك',
    'nav.findRoommate': 'ابحث عن شريك سكن',
    'nav.findRoommates': 'ابحث عن شركاء سكن',
    'nav.howItWorks': 'كيف يعمل',
    'nav.signIn': 'تسجيل الدخول',
    'nav.signOut': 'تسجيل الخروج',
    'nav.getStarted': 'ابدأ الآن',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    
    // Hero
    'hero.verifiedBadge': 'شركاء سكن موثقون وآمنون',
    'hero.title.part1': 'اعثر على',
    'hero.title.highlight': 'الغرفة',
    'hero.title.part2': 'أو',
    'hero.title.highlight2': 'شريك السكن',
    'hero.title.part3': 'المثالي في مصر',
    'hero.subtitle': 'سكنك يربطك بشركاء سكن موثقين ومتوافقين وغرف عالية الجودة. بدون سماسرة. بدون احتيال. فقط اتصالات موثوقة.',
    'hero.cta.findRoom': 'ابحث عن سكن',
    'hero.cta.listRoom': 'اعرض سكنك',
    'hero.badge.verified': 'مستخدمون موثقون فقط',
    'hero.badge.secure': 'دفع آمن',
    'hero.badge.support': 'دعم على مدار الساعة',
    'hero.badge.verified100': '١٠٠٪ موثق',
    'hero.stats.verified': 'مستخدمون موثقون',
    'hero.stats.members': '+١٠,٠٠٠ عضو',
    'hero.stats.listings': '+٥,٠٠٠ إعلان',
    'hero.card.title': 'غرفة حديثة في المعادي',
    'hero.card.price': '٣,٥٠٠ ج.م/شهرياً',
    
    // Room Card & Rooms
    'room.featured': 'مميز',
    'room.perMonth': '/شهرياً',
    'room.verified': 'موثق',
    'rooms.browseTitle': 'ابحث عن سكنك المثالي',
    'rooms.browseSubtitle': 'تصفح الأماكن الموثقة في مدن مصر',
    'rooms.searchPlaceholder': 'ابحث بالمدينة أو المنطقة أو العنوان...',
    'rooms.resultsFound': 'مكان موجود',
    'rooms.noResults': 'لم يتم العثور على أماكن',
    'rooms.noResultsHint': 'جرب تعديل الفلاتر أو البحث',
    'rooms.featured': 'مميز',
    'rooms.verified': 'إعلان موثق',
    'rooms.month': 'شهر',
    'rooms.privateRoom': 'غرفة خاصة',
    'rooms.sharedRoom': 'غرفة مشتركة',
    'rooms.studio': 'ستوديو',
    'rooms.apartment': 'شقة',
    'rooms.filters.title': 'الفلاتر',
    'rooms.filters.city': 'المدينة',
    'rooms.filters.allCities': 'جميع المدن',
    'rooms.filters.budget': 'الميزانية (ج.م/شهر)',
    'rooms.filters.min': 'الحد الأدنى',
    'rooms.filters.max': 'الحد الأقصى',
    'rooms.filters.roomType': 'نوع الغرفة',
    'rooms.filters.allTypes': 'جميع الأنواع',
    'rooms.filters.gender': 'الجنس المفضل',
    'rooms.filters.any': 'أي',
    'rooms.filters.allowsSmoking': 'التدخين مسموح',
    'rooms.filters.allowsPets': 'الحيوانات مسموحة',
    'rooms.filters.clear': 'مسح الفلاتر',
    'rooms.filters.done': 'تم',
    'rooms.filters.allGenders': 'جميع الأجناس',
     'rooms.delete': 'حذف',
     'rooms.deleteConfirmTitle': 'حذف الإعلان',
     'rooms.deleteConfirmDesc': 'هل أنت متأكد أنك تريد حذف هذا الإعلان؟ لا يمكن التراجع عن هذا الإجراء.',
     'rooms.deleteSuccess': 'تم حذف الإعلان بنجاح',
     'rooms.deleteError': 'فشل حذف الإعلان',

    // Room Details
    'roomDetails.backToRooms': 'العودة للإعلانات',
    'roomDetails.notFound': 'الإعلان غير موجود',
    'roomDetails.notFoundDesc': 'قد لا يكون هذا الإعلان متاحاً بعد الآن.',
    'roomDetails.browseRooms': 'تصفح الأماكن',
    'roomDetails.featured': 'مميز',
    'roomDetails.verifiedOwner': 'إعلان موثق',
    'roomDetails.malesOnly': 'للذكور فقط',
    'roomDetails.femalesOnly': 'للإناث فقط',
    'roomDetails.anyGender': 'أي جنس',
    'roomDetails.perMonth': 'شهرياً',
    'roomDetails.roommates': 'شركاء سكن',
    'roomDetails.minMonths': 'أشهر كحد أدنى',
    'roomDetails.deposit': 'تأمين',
    'roomDetails.none': 'لا يوجد',
    'roomDetails.aboutRoom': 'عن هذا المكان',
    'roomDetails.amenities': 'المرافق',
    'roomDetails.houseRules': 'قواعد المنزل',
    'roomDetails.smokingAllowed': 'التدخين مسموح',
    'roomDetails.noSmoking': 'ممنوع التدخين',
    'roomDetails.petsAllowed': 'الحيوانات مسموحة',
    'roomDetails.noPets': 'ممنوع الحيوانات',
    'roomDetails.listedBy': 'بواسطة',
    'roomDetails.roomOwner': 'صاحب الإعلان',
    'roomDetails.message': 'رسالة',
    'roomDetails.messageFailed': 'فشل بدء المحادثة. يرجى التحقق من حسابك.',
    'roomDetails.yourListing': 'هذا إعلانك',
    'roomDetails.cantReserveOwn': 'لا يمكنك حجز إعلانك الخاص.',
    'roomDetails.manageListing': 'إدارة الإعلان',
    
    // Reservation Form
    'reservation.title': 'احجز هذه الغرفة',
    'reservation.subtitle': 'احجز مكانك عن طريق الدفع',
    'reservation.checkInDate': 'تاريخ الدخول',
    'reservation.selectDate': 'اختر التاريخ',
    'reservation.duration': 'المدة (بالأشهر)',
    'reservation.minStay': 'الحد الأدنى للإقامة:',
    'reservation.months': 'أشهر',
    'reservation.priceBreakdown': 'تفاصيل السعر',
    'reservation.room': 'الغرفة',
    'reservation.month': 'شهر',
    'reservation.securityDeposit': 'مبلغ التأمين',
    'reservation.platformFee': 'رسوم المنصة (٥٪)',
    'reservation.total': 'الإجمالي',
    'reservation.protectedBy': 'محمي بواسطة سكنك',
    'reservation.protectedDesc': 'دفعتك آمنة. سيحصل المالك على المبلغ فقط بعد تأكيدك استلام الغرفة.',
    'reservation.processing': 'جاري المعالجة...',
    'reservation.pay': 'ادفع',
    'reservation.loginRequired': 'يرجى تسجيل الدخول لحجز هذه الغرفة',
    'reservation.created': 'تم إنشاء الحجز! جاري التحويل للدفع...',
    'reservation.failed': 'فشل إنشاء الحجز',
    'reservation.roomNotFound': 'الغرفة غير موجودة',
    'reservation.currency': 'ج.م',
    
    // Messages
    'messages.title': 'الرسائل',
    'messages.signInRequired': 'سجل الدخول لعرض الرسائل',
    'messages.signInDesc': 'يجب تسجيل الدخول للوصول إلى محادثاتك',
    'messages.signIn': 'تسجيل الدخول',
    'messages.allChatsProtected': 'جميع المحادثات محمية',
    'messages.selectConversation': 'اختر محادثة',
    'messages.selectConversationDesc': 'اختر محادثة من القائمة لبدء المراسلة',
    'messages.failedToLoad': 'فشل تحميل المحادثات',
    'messages.noConversations': 'لا توجد محادثات بعد',
    'messages.startChatting': 'ابدأ المحادثة بمراسلة مالك غرفة',
    'messages.unknownUser': 'مستخدم غير معروف',
    'messages.noMessagesYet': 'لا توجد رسائل بعد',
    'messages.you': 'أنت',
    'messages.conversationNotFound': 'المحادثة غير موجودة',
    'messages.protectedNotice': 'محمي بواسطة سكنك - مشاركة معلومات الاتصال محظورة لأمانك',
    'messages.noMessagesStart': 'لا توجد رسائل بعد. ابدأ المحادثة!',
    'messages.contentFiltered': 'تم تصفية المحتوى',
    'messages.yesterday': 'أمس',
    'messages.typeMessage': 'اكتب رسالة...',
    'messages.failedToSend': 'فشل إرسال الرسالة',
    
    // Testimonials
    'testimonials.title': 'ماذا يقول مستخدمونا',
    'testimonials.subtitle': 'قصص حقيقية من أشخاص وجدوا شريك السكن المثالي على سكنك',
    
    // Features
    'features.title': 'لماذا تختار سكنك؟',
    'features.verified.title': 'مستخدمون موثقون',
    'features.verified.desc': 'جميع المستخدمين يخضعون للتحقق من الهوية لسلامتك',
    'features.matching.title': 'مطابقة ذكية',
    'features.matching.desc': 'خوارزميتنا تجد غرف متوافقة بناءً على تفضيلاتك',
    'features.secure.title': 'مجاني 100% (لفترة محدودة)',
    'features.secure.desc': 'استخدم المنصة مجاناً الآن! لاحقاً، رسوم 5% على أول شهر فقط — تُخصم بعد انتقالك. إذا لم تنتقل، تسترد أموالك بالكامل.',
    'features.gender.title': 'أمان جنسي',
    'features.gender.desc': 'فلترة صارمة للجنس تضمن ترتيبات سكن مريحة',
    
    // How It Works
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.step1.title': 'أنشئ ملفك',
    'howItWorks.step1.desc': 'سجل وتحقق من هويتك',
    'howItWorks.step2.title': 'تصفح القوائم',
    'howItWorks.step2.desc': 'ابحث عن غرف أو شركاء سكن يناسبون تفضيلاتك',
    'howItWorks.step3.title': 'احجز معاينة',
    'howItWorks.step3.desc': 'حدد موعد معاينة مع المضيف وزُر المكان شخصياً',
    'howItWorks.step4.title': 'انتقل',
    'howItWorks.step4.desc': 'أكد الاتفاق وابدأ فصلك الجديد — مجاني 100% حالياً!',
    
    // CTA Section
    'cta.title': 'مستعد للعثور على مكانك المثالي؟',
    'cta.subtitle': 'تصفح غرف وشركاء سكن موثقين في مصر — بدون تسجيل للاستكشاف',
    'cta.button': 'تصفح الغرف الآن',
    
    // Footer
    'footer.description': 'المنصة الموثوقة للعثور على غرف وشركاء سكن في مصر.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.support': 'الدعم',
    'footer.legal': 'قانوني',
    'footer.contact': 'اتصل بنا',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.safety': 'نصائح السلامة',
    'footer.terms': 'الشروط والأحكام',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.refund': 'سياسة الاسترداد',
    'footer.rights': 'جميع الحقوق محفوظة.',

    // Auth
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.createAccountTitle': 'إنشاء حسابك',
    'auth.loginSubtitle': 'سجل الدخول للمتابعة إلى سكنك',
    'auth.signupSubtitle': 'انضم إلى آلاف المستخدمين الموثقين',
    'auth.fullName': 'الاسم الكامل',
    'auth.fullNamePlaceholder': 'أدخل اسمك الكامل',
    'auth.email': 'البريد الإلكتروني',
    'auth.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.passwordPlaceholder': 'أدخل كلمة المرور',
    'auth.gender': 'الجنس',
    'auth.genderNote': 'لا يمكن تغييره لاحقاً ويستخدم للمطابقة',
    'auth.male': 'ذكر',
    'auth.female': 'أنثى',
    'auth.signIn': 'تسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signUpLink': 'سجل الآن',
    'auth.signInLink': 'تسجيل الدخول',
    'auth.termsText': 'بإنشاء حساب، فإنك توافق على',
    'auth.termsLink': 'الشروط والأحكام',
    'auth.and': 'و',
    'auth.privacyLink': 'سياسة الخصوصية',
    'auth.brandTitle': 'اعثر على غرفتك أو شريك سكنك المثالي في مصر',
    'auth.brandSubtitle': 'انضم إلى المجتمع الموثوق من المستخدمين الذين يبحثون عن أماكن سكن آمنة ومتوافقة.',
    'auth.feature1': 'مستخدمون موثقون بالهوية فقط',
    'auth.feature2': '+٥,٠٠٠ إعلان عالي الجودة',
    'auth.error.invalidCredentials': 'بريد إلكتروني أو كلمة مرور غير صحيحة. حاول مرة أخرى.',
    'auth.error.emailNotConfirmed': 'يرجى التحقق من بريدك الإلكتروني قبل تسجيل الدخول.',
    'auth.error.alreadyRegistered': 'هذا البريد مسجل بالفعل. يرجى تسجيل الدخول.',
    'auth.error.rateLimitExceeded': 'محاولات كثيرة جداً. يرجى الانتظار بضع دقائق والمحاولة مرة أخرى.',
    'auth.resendEmail': 'إعادة إرسال بريد التحقق',
    'auth.resendEmailSending': 'جاري الإرسال...',
    'auth.resendEmailSuccess': 'تم إرسال بريد التحقق! يرجى التحقق من بريدك الوارد.',
    'auth.success.checkEmail': 'تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني لتفعيل حسابك.',
    'auth.success.checkStudentEmail': 'تم إنشاء حساب الطالب! يرجى التحقق من بريدك الجامعي لتفعيل حسابك. سيتم التحقق من حالة الطالب تلقائياً.',
    'auth.or': 'أو',
    'auth.continueWithGoogle': 'المتابعة مع جوجل',
    'auth.continueWithApple': 'المتابعة مع Apple',
    'auth.joinAsStudent': 'الانضمام كطالب',
    'auth.studentSignupTitle': 'الانضمام كطالب',
    'auth.studentSignupSubtitle': 'سجل ببريدك الجامعي للحصول على التحقق تلقائياً',
    'auth.studentEmail': 'البريد الجامعي',
    'auth.studentEmailPlaceholder': 'اسمك@الجامعة.edu.eg',
    'auth.studentEmailError': 'يرجى استخدام بريد جامعي صالح (.edu, .edu.eg, .ac, إلخ)',
    'auth.backToSignup': 'العودة للتسجيل العادي',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.resetPassword': 'إعادة تعيين كلمة المرور',
    'auth.resetPasswordSubtitle': 'أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين',
    'auth.sendResetLink': 'إرسال رابط إعادة التعيين',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'auth.resetEmailSent': 'تم إرسال بريد إعادة تعيين كلمة المرور! تحقق من بريدك الوارد.',
    
    // Reset Password Page
    'resetPassword.title': 'تعيين كلمة مرور جديدة',
    'resetPassword.subtitle': 'أدخل كلمة المرور الجديدة أدناه',
    'resetPassword.newPassword': 'كلمة المرور الجديدة',
    'resetPassword.newPasswordPlaceholder': 'أدخل كلمة المرور الجديدة',
    'resetPassword.confirmPassword': 'تأكيد كلمة المرور',
    'resetPassword.confirmPasswordPlaceholder': 'أكد كلمة المرور الجديدة',
    'resetPassword.updatePassword': 'تحديث كلمة المرور',
    'resetPassword.passwordsMustMatch': 'كلمتا المرور غير متطابقتين',
    'resetPassword.success': 'تم تحديث كلمة المرور بنجاح! جاري التحويل...',
    'resetPassword.invalidLink': 'رابط إعادة التعيين غير صالح',
    'resetPassword.invalidLinkDesc': 'رابط إعادة تعيين كلمة المرور غير صالح أو منتهي الصلاحية. يرجى طلب رابط جديد.',
    'resetPassword.backToLogin': 'العودة لتسجيل الدخول',
    
    'auth.nationality': 'الجنسية',
    'auth.selectNationality': 'اختر جنسيتك',

    // Profile
    'profile.edit': 'تعديل الملف',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.updateSuccess': 'تم تحديث الملف بنجاح',
    'profile.updateError': 'فشل تحديث الملف',
    'profile.verified': 'موثق',
    'profile.pending': 'قيد التحقق',
    'profile.rejected': 'مرفوض',
    'profile.unverified': 'غير موثق',
    'profile.phone': 'رقم الهاتف',
    'profile.whatsapp': 'واتساب',
    'profile.nationality': 'الجنسية',
    'profile.occupation': 'المهنة',
    'profile.about': 'نبذة عني',
    'profile.aboutPlaceholder': 'أخبر الآخرين عن نفسك ونمط حياتك وما تبحث عنه...',
    'profile.lookingFor': 'أبحث عن',
    'profile.lookingForPlaceholder': 'مثال: غرفة قريبة من وسط المدينة، شريك سكن هادئ...',
    'profile.isSmoker': 'أنا مدخن',
    'profile.hasPets': 'لدي حيوانات أليفة',
    'profile.petType': 'نوع الحيوان',
    'profile.petTypePlaceholder': 'مثال: قطة، كلب...',
    'profile.smoker': 'مدخن',
    'profile.myListings': 'إعلاناتي',
    'profile.savedRooms': 'الغرف المحفوظة',
    'profile.addListing': 'إضافة إعلان',
    'profile.noListings': 'لم تضف أي غرف بعد',
    'profile.noSaved': 'لم تحفظ أي غرف بعد',
    'profile.browseRooms': 'تصفح الغرف',
     'profile.changePassword.title': 'تغيير كلمة المرور',
     'profile.changePassword.description': 'قم بتحديث كلمة المرور للحفاظ على أمان حسابك',
     'profile.changePassword.current': 'كلمة المرور الحالية',
     'profile.changePassword.new': 'كلمة المرور الجديدة',
     'profile.changePassword.confirm': 'تأكيد كلمة المرور الجديدة',
     'profile.changePassword.requirements': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
     'profile.changePassword.minLength': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
     'profile.changePassword.mismatch': 'كلمتا المرور غير متطابقتين',
     'profile.changePassword.samePassword': 'يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية',
     'profile.changePassword.match': 'كلمتا المرور متطابقتان',
     'profile.changePassword.submit': 'تحديث كلمة المرور',
     'profile.changePassword.success': 'تم تحديث كلمة المرور بنجاح',
     'profile.changePassword.error': 'فشل تحديث كلمة المرور',

    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.loading': 'جاري التحميل...',
    'common.unknown': 'غير معروف',

    // Room Form
    'rooms.form.title': 'أضف سكنك',
    'rooms.form.subtitle': 'أدخل تفاصيل سكنك للعثور على شريك السكن المثالي',
    'rooms.form.loginRequired': 'يرجى تسجيل الدخول لإضافة إعلان',
    'rooms.form.verificationRequired': 'يجب أن تكون موثقاً لإضافة إعلان',
    'rooms.form.verificationNotice': 'يجب التحقق من حسابك قبل إضافة إعلانات. يرجى إكمال التحقق.',
    'rooms.form.verifiedNotice': 'أنت موثق ويمكنك إضافة إعلانات!',
    'rooms.form.basicInfo': 'معلومات أساسية',
    'rooms.form.basicInfoDesc': 'أدخل التفاصيل الأساسية عن سكنك',
    'rooms.form.roomTitle': 'العنوان',
    'rooms.form.roomTitlePlaceholder': 'مثال: غرفة خاصة حديثة في المعادي',
    'rooms.form.description': 'الوصف',
    'rooms.form.descriptionPlaceholder': 'صف سكنك والشقة والحي...',
    'rooms.form.roomType': 'نوع الغرفة',
    'rooms.form.price': 'السعر (ج.م/شهر)',
    'rooms.form.location': 'الموقع',
    'rooms.form.locationDesc': 'أين يقع سكنك؟',
    'rooms.form.city': 'المدينة',
    'rooms.form.selectCity': 'اختر مدينة',
    'rooms.form.area': 'المنطقة',
    'rooms.form.areaPlaceholder': 'مثال: المعادي، الزمالك',
    'rooms.form.address': 'العنوان',
    'rooms.form.addressPlaceholder': 'عنوان الشارع',
    'rooms.form.photos': 'الصور',
    'rooms.form.photosDesc': 'ارفع حتى ٦ صور لسكنك',
    'rooms.form.addPhoto': 'إضافة صورة',
    'rooms.form.photosUploaded': 'صور مرفوعة',
    'rooms.form.invalidImage': 'يرجى اختيار ملف صورة صالح',
    'rooms.form.imageTooLarge': 'يجب أن تكون الصورة أقل من ٥ ميجابايت',
    'rooms.form.uploadError': 'فشل رفع الصورة',
    'rooms.form.amenitiesRules': 'المرافق والقواعد',
    'rooms.form.amenitiesRulesDesc': 'ماذا يوفر سكنك وما هي قواعد المنزل؟',
    'rooms.form.amenities': 'المرافق',
    'rooms.form.addAmenity': 'أضف مرفق...',
    'rooms.form.rules': 'قواعد المنزل',
    'rooms.form.addRule': 'أضف قاعدة...',
    'rooms.form.availability': 'التوفر والتفضيلات',
    'rooms.form.availabilityDesc': 'متى يتوفر السكن ومن تبحث عنه؟',
    'rooms.form.availableFrom': 'متاح من',
    'rooms.form.pickDate': 'اختر تاريخ',
    'rooms.form.minStay': 'الحد الأدنى للإقامة (أشهر)',
    'rooms.form.maxRoommates': 'أقصى عدد شركاء السكن',
    'rooms.form.currentRoommates': 'شركاء السكن الحاليون',
    'rooms.form.preferredGender': 'الجنس المفضل',
    'rooms.form.allowsSmoking': 'التدخين مسموح',
    'rooms.form.allowsPets': 'الحيوانات مسموحة',
    'rooms.form.requiredFields': 'يرجى ملء جميع الحقول المطلوبة',
    'rooms.form.success': 'تم إضافة الإعلان بنجاح!',
    'rooms.form.error': 'فشل إضافة الإعلان. حاول مرة أخرى.',
    'rooms.form.creating': 'جاري إنشاء الإعلان...',
    'rooms.form.submit': 'إضافة الإعلان',
    'rooms.form.yes': 'نعم',
    'rooms.form.no': 'لا',
    'rooms.form.acceptSmokers': 'التدخين مسموح',
    'rooms.form.acceptPets': 'الحيوانات مسموحة',
    // New amenity fields
    'rooms.form.amenitiesDesc': 'اختر المرافق المتوفرة في سكنك',
    'rooms.form.naturalGas': 'غاز طبيعي',
    'rooms.form.wifi': 'واي فاي متاح',
    'rooms.form.elevator': 'مصعد',
    'rooms.form.balcony': 'بلكونة',
    'rooms.form.doorman': 'بواب/أمن',
    'rooms.form.ac': 'تكييف هواء',
    'rooms.form.waterHeater': 'سخان مياه',
    // House rules
    'rooms.form.houseRules': 'قواعد المنزل',
    'rooms.form.houseRulesDesc': 'حدد قواعد سكنك',
    'rooms.form.allowsVisits': 'الزيارات مسموحة',
    // Capacity fields
    'rooms.form.capacity': 'السعة',
    'rooms.form.capacityDesc': 'حدد سعة الغرفة والإشغال الحالي',
    'rooms.form.totalBedrooms': 'إجمالي غرف النوم',
    'rooms.form.totalBedroomsHint': 'عدد غرف النوم الإجمالي في الشقة',
    'rooms.form.currentOccupants': 'الساكنون الحاليون',
    'rooms.form.currentOccupantsHint': 'عدد الأشخاص الذين يسكنون حالياً',
    // Location link
    'rooms.form.locationLink': 'رابط الموقع',
    'rooms.form.locationLinkPlaceholder': 'الصق رابط خرائط جوجل أو آبل',
    'rooms.form.locationLinkHint': 'شارك رابط خريطة ليتمكن المشاهدون من إيجاد الموقع بسهولة',
    'rooms.form.locationPrivacyNotice': 'موقعك الدقيق خاص وسيتم مشاركته فقط مع المستأجرين بعد تأكيد موعد المعاينة.',

    // Verification
    'verification.title': 'تحقق من هويتك',
    'verification.subtitle': 'ارفع وثيقة هوية صالحة للتحقق وفتح جميع الميزات',
    'verification.whyVerify': 'المستخدمون الموثقون يمكنهم إضافة غرف وموثوق بهم من المجتمع. يتم تخزين هويتك بشكل آمن ومراجعتها من قبل فريقنا.',
    'verification.verified': 'تم التحقق من الهوية',
    'verification.verifiedDesc': 'حسابك موثق. يمكنك إضافة غرف والوصول لجميع الميزات.',
    'verification.pending': 'التحقق قيد المراجعة',
    'verification.pendingDesc': 'يتم مراجعة وثائقك. يستغرق هذا عادة ٢٤-٤٨ ساعة.',
    'verification.rejected': 'تم رفض التحقق',
    'verification.rejectedDesc': 'تم رفض طلب التحقق. يرجى المحاولة مرة أخرى بوثيقة أوضح.',
    'verification.reason': 'السبب',
    'verification.documentType': 'نوع الوثيقة',
    'verification.nationalId': 'بطاقة الهوية الوطنية',
    'verification.passport': 'جواز السفر',
    'verification.driverLicense': 'رخصة القيادة',
    'verification.uploadDocument': 'ارفع الوثيقة',
    'verification.dragOrClick': 'انقر أو اسحب للرفع',
    'verification.maxSize': 'الحجم الأقصى: ١٠ ميجابايت (صور أو PDF)',
    'verification.clickToChange': 'انقر لتغيير الملف',
    'verification.selectDocument': 'يرجى اختيار وثيقة للرفع',
    'verification.fileTooLarge': 'الملف كبير جداً. الحجم الأقصى ١٠ ميجابايت.',
    'verification.invalidFileType': 'نوع ملف غير صالح. يرجى رفع صورة أو PDF.',
    'verification.submit': 'إرسال للتحقق',
    'verification.submitting': 'جاري الإرسال...',
    'verification.submitSuccess': 'تم إرسال طلب التحقق! سنراجعه خلال ٢٤-٤٨ ساعة.',
    'verification.submitError': 'فشل إرسال التحقق. يرجى المحاولة مرة أخرى.',
    'verification.cancel': 'إلغاء الطلب',
    'verification.cancelSuccess': 'تم إلغاء طلب التحقق.',
    'verification.cancelError': 'فشل إلغاء الطلب.',
     'verification.frontPhoto': 'وجه الهوية',
     'verification.backPhoto': 'ظهر الهوية',
     'verification.uploadFront': 'ارفع الوجه الأمامي للهوية',
     'verification.uploadBack': 'ارفع الوجه الخلفي للهوية',
     'verification.selectBothDocuments': 'يرجى رفع صورة الوجه الأمامي والخلفي للهوية',

    // Admin
    'admin.verificationTitle': 'طلبات التحقق',
    'admin.verificationSubtitle': 'مراجعة وإدارة طلبات تحقق المستخدمين',
    'admin.allRequests': 'جميع الطلبات',
    'admin.pending': 'قيد الانتظار',
    'admin.approved': 'موافق عليه',
    'admin.rejected': 'مرفوض',
    'admin.submittedOn': 'أرسل في',
    'admin.viewDocument': 'عرض الوثيقة',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.approveSuccess': 'تم التحقق من المستخدم بنجاح!',
    'admin.approveError': 'فشل الموافقة على التحقق.',
    'admin.rejectSuccess': 'تم رفض التحقق.',
    'admin.rejectError': 'فشل رفض التحقق.',
    'admin.rejectTitle': 'رفض التحقق',
    'admin.rejectReasonLabel': 'سبب الرفض',
    'admin.rejectReasonPlaceholder': 'اشرح سبب رفض التحقق...',
    'admin.rejectReasonRequired': 'يرجى تقديم سبب للرفض.',
    'admin.confirmReject': 'تأكيد الرفض',
    'admin.noRequests': 'لا توجد طلبات تحقق',
    'admin.noRequestsHint': 'لا توجد طلبات تطابق الفلتر الخاص بك.',
    'admin.accessDenied': 'الوصول مرفوض',
    'admin.accessDeniedDesc': 'ليس لديك صلاحية للوصول لهذه الصفحة. صلاحيات المسؤول مطلوبة.',
     'admin.viewFront': 'عرض الوجه',
     'admin.viewBack': 'عرض الظهر',

    // Roommates
    'roommates.title': 'ابحث عن شريك سكن',
    'roommates.subtitle': 'تصفح شركاء السكن الموثقين مع المطابقة الذكية. اعثر على شخص يشاركك تفضيلات نمط الحياة.',
    'roommates.searchPlaceholder': 'ابحث بالاسم أو المهنة أو الاهتمامات...',
    'roommates.resultsFound': 'شريك سكن موجود',
    'roommates.noResults': 'لم يتم العثور على شركاء سكن',
    'roommates.noResultsHint': 'جرب تعديل الفلاتر أو عد لاحقاً. يتم إضافة مستخدمين موثقين جدد بانتظام.',
    'roommates.signInNotice': 'سجل الدخول لمطابقات أفضل',
    'roommates.signInDesc': 'سجل الدخول لرؤية نسب التوافق المخصصة بناءً على ملفك الشخصي.',
    'roommates.viewProfile': 'عرض الملف',
    'roommates.message': 'رسالة',
    'roommates.compatibility': 'التوافق',
    'roommates.bestMatch': 'أفضل تطابق',
    'roommates.about': 'نبذة',
    'roommates.lookingFor': 'يبحث عن',
    'roommates.memberSince': 'عضو منذ',
    'roommates.sendMessage': 'إرسال رسالة',
    'roommates.interestedConnect': 'مهتم بالتواصل؟',
    'roommates.signInToMessage': 'سجل الدخول لمراسلة هذا الشريك ورؤية نسب التوافق.',
    'roommates.back': 'العودة لشركاء السكن',
    'roommates.notFound': 'شريك السكن غير موجود',
    'roommates.notFoundDesc': 'هذا الملف قد لا يكون موجوداً أو غير متاح.',
    'roommates.smoker': 'مدخن',
    'roommates.nonSmoker': 'غير مدخن',
    'roommates.hasPets': 'لديه حيوانات أليفة',
    'roommates.filters.search': 'بحث',
    'roommates.filters.searchPlaceholder': 'ابحث بالاسم أو النبذة أو المهنة...',
    'roommates.filters.occupation': 'المهنة',
    'roommates.filters.occupationPlaceholder': 'مثال: طالب، مهندس...',
    'roommates.filters.smoker': 'مدخن',
    'roommates.filters.hasPets': 'لديه حيوانات',
    'roommates.filters.clear': 'مسح الفلاتر',
    'roommates.filters.title': 'الفلاتر',

    // Payment Settings
    'payment.settings': 'إعدادات الدفع',
    'payment.settingsDesc': 'حدد مبلغ التأمين وطريقة الاستلام المفضلة',
    'payment.insurance': 'مبلغ التأمين/الضمان (ج.م)',
    'payment.insuranceDesc': 'سيتم تحصيل هذا المبلغ من الباحث كوديعة ضمان',
    'payment.payoutMethod': 'طريقة الاستلام',
    'payment.payoutMethodDesc': 'كيف تريد استلام دفعتك بعد تأكيد الباحث',
    'payment.instapay': 'انستاباي',
    'payment.vodafoneCash': 'فودافون كاش',
    'payment.fawry': 'فوري',
    'payment.payoutDetails': 'تفاصيل الاستلام',
    'payment.instapayPlaceholder': 'أدخل رقم هاتف انستاباي أو IPA',
    'payment.vodafonePlaceholder': 'أدخل رقم فودافون كاش (مثل: 01xxxxxxxxx)',
    'payment.fawryPlaceholder': 'أدخل رقم فوري المرجعي أو رقم الهاتف',
    'payment.payoutDetailsDesc': 'هنا سنرسل دفعتك. تأكد من صحته!',
    'payment.flowTitle': 'مسار الدفع',
    'payment.flowStep1': 'الباحث يدفع سعر الغرفة + التأمين (خصم ٥٪ رسوم المنصة)',
    'payment.flowStep2': 'عندما يؤكد الباحث استلامه الغرفة، تستلم دفعتك',
    'payment.flowStep3': 'يتم إرسال الدفعة بالطريقة المختارة أعلاه',


    // Viewing
    'viewing.bookTitle': 'احجز معاينة',
    'viewing.selectDate': 'اختر التاريخ',
    'viewing.pickDate': 'اختر تاريخ',
    'viewing.preferredTime': 'الوقت المفضل',
    'viewing.selectTime': 'اختر',
    'viewing.duration': 'المدة',
    'viewing.message': 'رسالة (اختياري)',
    'viewing.messagePlaceholder': 'أي أسئلة أو طلبات محددة...',
    'viewing.messageNote': 'لا يُسمح بأرقام الهاتف أو البريد الإلكتروني أو الروابط',
    'viewing.noContactInfo': 'معلومات الاتصال (هاتف، بريد إلكتروني، روابط) غير مسموح بها',
    'viewing.sendRequest': 'إرسال طلب المعاينة',
    'viewing.verificationRequired': 'يجب التحقق من هويتك قبل حجز المعاينات. يرجى إكمال التحقق في ملفك الشخصي.',

    // My Viewings Page
    'viewings.myViewings': 'معايناتي',
    'viewings.manageViewings': 'إدارة مواعيد معاينة العقارات الخاصة بك',
    'viewings.asTenant': 'كمستأجر',
    'viewings.asLandlord': 'كمالك',
    'viewings.active': 'المعاينات النشطة',
    'viewings.past': 'المعاينات السابقة',
    'viewings.noViewings': 'لا توجد معاينات بعد',
    'viewings.noViewingsDescription': 'تصفح الغرف واحجز معاينة للبدء.',
    'viewings.browseRooms': 'تصفح الغرف',
    'viewings.pendingRequests': 'الطلبات المعلقة',
    'viewings.scheduled': 'المعاينات المجدولة',
    'viewings.noRequests': 'لا توجد طلبات معاينة',
    'viewings.noRequestsDescription': 'عندما يطلب المستأجرون معاينة غرفك، ستظهر هنا.',
    'viewings.atProperty': 'في العقار؟',
    'viewings.markArrivedDescription': 'أكد وصولك لفتح خيارات تأكيد الإيجار.',
    'viewings.imHere': 'أنا هنا',
    'viewings.viewing': 'معاينة',

    // Viewing Card
    'viewing.landlord': 'المالك',
    'viewing.tenant': 'المستأجر',
    'viewing.proposedTime': 'الوقت المقترح',
    'viewing.confirmedTime': 'الوقت المؤكد',
    'viewing.newTimeProposed': 'تم اقتراح وقت جديد',
    'viewing.originalTime': 'الأصلي',
    'viewing.tenantMessage': 'رسالة المستأجر',
    'viewing.landlordResponse': 'رد المالك',
    'viewing.locationShared': 'تم مشاركة الموقع عبر المحادثة',
    'viewing.confirm': 'تأكيد',
    'viewing.proposeNewTime': 'وقت جديد',
    'viewing.shareLocation': 'مشاركة الموقع',
    'viewing.acceptTime': 'قبول الوقت',
    'viewing.cancel': 'إلغاء',
    'viewing.confirmRental': 'تأكيد الإيجار',
    'viewing.decline': 'رفض',
    'viewing.chat': 'المحادثة',
    'viewing.chatLocked': 'المحادثة مغلقة',
    'viewing.chatUnlocksAfterConfirm': 'ستفتح المحادثة بعد تأكيد موعد المعاينة من الطرفين',
    'viewing.chatWithLandlord': 'محادثة مع المالك',
    'viewing.chatWithTenant': 'محادثة مع المستأجر',
    'viewing.startChatting': 'ابدأ المحادثة لتنسيق موعد المعاينة',
    'viewing.noPhoneEmail': 'لا يُسمح بأرقام الهاتف أو البريد الإلكتروني',

    // Q&A
    'qa.title': 'الأسئلة والأجوبة',
    'qa.askPlaceholder': 'اطرح سؤالاً عن هذا الإعلان...',
    'qa.verifyFirst': 'تحقق من حسابك لطرح الأسئلة',
    'qa.askButton': 'اطرح سؤالاً',
    'qa.ownerAnswer': 'المالك',
    'qa.answerPlaceholder': 'اكتب إجابتك...',
    'qa.postAnswer': 'نشر الإجابة',
    'qa.answerButton': 'أجب',
    'qa.awaitingAnswer': 'في انتظار رد المالك',
    'qa.noQuestions': 'لا توجد أسئلة بعد. كن أول من يسأل!',

    // Counter Propose Dialog
    'viewing.proposeNewTimeTitle': 'اقتراح وقت جديد',
    'viewing.counterProposeDescription': 'اقترح وقتاً بديلاً يناسبك بشكل أفضل.',
    'viewing.originalRequest': 'الطلب الأصلي',
    'viewing.newDate': 'التاريخ الجديد',
    'viewing.responseMessage': 'رسالة (اختياري)',
    'viewing.responseMessagePlaceholder': 'اشرح لماذا هذا الوقت أفضل...',
    'viewing.sendProposal': 'إرسال الاقتراح',
    'viewing.alreadyRequested': 'لديك بالفعل طلب معاينة نشط لهذه الغرفة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sakanak-language');
    return (saved === 'ar' || saved === 'en') ? saved : 'en';
  });

  const isRTL = language === 'ar';

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('sakanak-language', lang);
  };

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
